//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan
    {
        public int ActionPlanId { get; set; }
        public int KRAEvalId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public int Responsible { get; set; }
        public int Status { get; set; }
        public int Created_By { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual KRAEvaluation KRAEvaluation { get; set; }
    }
}
