//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppNotification()
        {
            this.AppNotification1 = new HashSet<AppNotification>();
        }
    
        public int AppNotificationId { get; set; }
        public int SenderEmpId { get; set; }
        public string SenderDeviceId { get; set; }
        public string SenderImagePath { get; set; }
        public int ReceiverEmpId { get; set; }
        public string ReceiverDeviceId { get; set; }
        public Nullable<int> ReceiverDevicePlatforms { get; set; }
        public string NotificationTitle { get; set; }
        public string Message { get; set; }
        public string NotificationMediaPath { get; set; }
        public Nullable<int> NotificationMediaType { get; set; }
        public bool IsRead { get; set; }
        public int NotificationType { get; set; }
        public bool Status { get; set; }
        public Nullable<int> ParentAppNotificationId { get; set; }
        public bool IsReplied { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppNotification> AppNotification1 { get; set; }
        public virtual AppNotification AppNotification2 { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
