//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceReprotParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceReprotParameter()
        {
            this.AttendanceReportDepartmentLookups = new HashSet<AttendanceReportDepartmentLookup>();
            this.EmployeePLBalanceDetails = new HashSet<EmployeePLBalanceDetail>();
            this.tblAttendanceReportPLBalances = new HashSet<tblAttendanceReportPLBalance>();
        }
    
        public int AttendanceReportParameterId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> CreaetdDate { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DataFreezingDateTime { get; set; }
        public bool IsPayrollDataTransfer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceReportDepartmentLookup> AttendanceReportDepartmentLookups { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePLBalanceDetail> EmployeePLBalanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceReportPLBalance> tblAttendanceReportPLBalances { get; set; }
    }
}
