//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankMaster()
        {
            this.companies = new HashSet<company>();
            this.employees = new HashSet<employee>();
            this.employeeReplicas = new HashSet<employeeReplica>();
        }
    
        public int BankId { get; set; }
        public string BankName { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Bankcode { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string RTGSCode { get; set; }
        public string NEFTCode { get; set; }
        public string IFSCCode { get; set; }
        public string ECSCode { get; set; }
        public string MICRCode { get; set; }
        public string BankBranch { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company> companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeeReplica> employeeReplicas { get; set; }
    }
}
