//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_employees_O2H_20171106
    {
        public int employee_id { get; set; }
        public string employee_code { get; set; }
        public string employee_fname { get; set; }
        public string employee_lname { get; set; }
        public string gender { get; set; }
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> designation_id { get; set; }
        public Nullable<int> grade_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public Nullable<System.DateTime> resig_date { get; set; }
        public Nullable<System.DateTime> left_date { get; set; }
        public Nullable<System.DateTime> retire_date { get; set; }
        public string birth_Place { get; set; }
        public string card_no { get; set; }
        public string EmployeeRFIDNumber { get; set; }
        public string employment_type { get; set; }
        public string EmployeeDevicePassword { get; set; }
        public string EmployeeDeviceGroup { get; set; }
        public string father_fname { get; set; }
        public string father_lname { get; set; }
        public string monther_fname { get; set; }
        public string monther_lname { get; set; }
        public string res_address1 { get; set; }
        public string res_address2 { get; set; }
        public Nullable<int> res_country_id { get; set; }
        public Nullable<int> res_state_id { get; set; }
        public Nullable<int> res_city_id { get; set; }
        public string res_pincode { get; set; }
        public string per_address1 { get; set; }
        public string per_address2 { get; set; }
        public Nullable<int> per_country_id { get; set; }
        public Nullable<int> per_state_id { get; set; }
        public Nullable<int> per_city_id { get; set; }
        public string per_pincode { get; set; }
        public string res_phone_no { get; set; }
        public string res_mobile_no { get; set; }
        public string email { get; set; }
        public Nullable<int> bloodgroup { get; set; }
        public string physical_status { get; set; }
        public string extension_no { get; set; }
        public string login_name { get; set; }
        public string login_password { get; set; }
        public Nullable<int> holiday_group { get; set; }
        public Nullable<int> leave_group { get; set; }
        public Nullable<int> paygroup_id { get; set; }
        public Nullable<int> shift_groupid { get; set; }
        public string ot_alwd { get; set; }
        public Nullable<int> ot_grp_id { get; set; }
        public string bonus_alwd { get; set; }
        public Nullable<int> bonus_grp_id { get; set; }
        public Nullable<int> shift_roasterid { get; set; }
        public string marital_status { get; set; }
        public Nullable<int> nationality { get; set; }
        public Nullable<int> religion { get; set; }
        public Nullable<int> Social_Status { get; set; }
        public string machine_no { get; set; }
        public string bank_account { get; set; }
        public string bank_name { get; set; }
        public string bank_branch_name { get; set; }
        public string code_ifsc { get; set; }
        public string reason_resign { get; set; }
        public string pf_alwd { get; set; }
        public string pf_no { get; set; }
        public string esi_alwd { get; set; }
        public string esi_no { get; set; }
        public Nullable<System.DateTime> Marriage_Date { get; set; }
        public string Emergency_No { get; set; }
        public string spouse_fname { get; set; }
        public string spouse_Lname { get; set; }
        public string passport_no { get; set; }
        public Nullable<System.DateTime> passport_valid_dt { get; set; }
        public string drive_licence_no { get; set; }
        public Nullable<System.DateTime> drive_licence_date { get; set; }
        public string drive_badge_Number { get; set; }
        public Nullable<System.DateTime> drive_badge_exp_date { get; set; }
        public string Election_card_number { get; set; }
        public Nullable<decimal> Emp_Height_cms { get; set; }
        public string Emp_identy_mark { get; set; }
        public string Emp_DoctorName { get; set; }
        public string Emp_lwf_number { get; set; }
        public Nullable<int> Total_child { get; set; }
        public Nullable<int> Total_child_studying { get; set; }
        public string dev_admin { get; set; }
        public Nullable<int> shift_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string allowed_location { get; set; }
        public string mode_of_payment { get; set; }
        public string autoshift_alwd { get; set; }
        public string compoff_alwd { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> del_time { get; set; }
        public Nullable<int> del_by { get; set; }
        public string aadhar_no { get; set; }
    }
}
