//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequest
    {
        public int ID { get; set; }
        public int ChangeRequestId { get; set; }
        public Nullable<System.DateTime> InitiatedOn { get; set; }
        public string InitiatedBy { get; set; }
        public string Description { get; set; }
        public string ImpactedFunctionality { get; set; }
        public string ReasonForChange { get; set; }
        public Nullable<int> SDLCPhase { get; set; }
        public Nullable<int> PriorityOfChangeId { get; set; }
        public Nullable<int> LevelOfChangeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string RejectionDeferredDate { get; set; }
        public string ReasonForRejectionDeferred { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedDate { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> ImpactOnEffort { get; set; }
        public Nullable<decimal> EstimatedHours { get; set; }
        public Nullable<decimal> ActualHours { get; set; }
        public Nullable<int> ImpactOnSchedule { get; set; }
        public string PlannedDeliveryDate { get; set; }
        public string ReviewedBy { get; set; }
        public string ReviewedDate { get; set; }
        public string TestingBy { get; set; }
        public string TestingDate { get; set; }
        public string ReleaseVersion { get; set; }
        public string ReleaseDate { get; set; }
        public Nullable<int> ClientAcceptance { get; set; }
        public string ClientAcceptanceReference { get; set; }
        public string Remarks { get; set; }
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> Entereddatetime { get; set; }
    }
}
