//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequestPaymentMilestone
    {
        public int ChangeRequestMilestoneID { get; set; }
        public int CRID { get; set; }
        public string PaymentMilestones { get; set; }
        public decimal PaymentPercent { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string AcceptanceNote { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
    
        public virtual tblChangeRequestMaster tblChangeRequestMaster { get; set; }
    }
}
