//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.clientcontacts = new HashSet<clientcontact>();
            this.projects = new HashSet<project>();
            this.projectinitiations = new HashSet<projectinitiation>();
            this.tblPINOpportunitiesMasters = new HashSet<tblPINOpportunitiesMaster>();
        }
    
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public int CountryID { get; set; }
        public string BusinessPhoneNumber1 { get; set; }
        public string BusinessPhoneNumber2 { get; set; }
        public string CellNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string ChatID { get; set; }
        public string FaxNumber { get; set; }
        public string GUID { get; set; }
        public string ClientBackground { get; set; }
        public string ClientType { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientcontact> clientcontacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPINOpportunitiesMaster> tblPINOpportunitiesMasters { get; set; }
    }
}
