//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnsMaster_NewReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColumnsMaster_NewReport()
        {
            this.EmployeeColumnsReportMapping_NewReport = new HashSet<EmployeeColumnsReportMapping_NewReport>();
        }
    
        public int ColumnsId { get; set; }
        public string ColumnsName { get; set; }
        public string ColumnsValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeColumnsReportMapping_NewReport> EmployeeColumnsReportMapping_NewReport { get; set; }
    }
}
