//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceRoomEquipmentDetail
    {
        public long ConferenceRoomEquipmentId { get; set; }
        public long ConferenceRoomId { get; set; }
        public long EquipmentId { get; set; }
    
        public virtual ConferenceRoomMaster ConferenceRoomMaster { get; set; }
    }
}
