//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrencyDefinition()
        {
            this.projectinitiations = new HashSet<projectinitiation>();
        }
    
        public int CurrencyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CurrencyName { get; set; }
        public string Symbols { get; set; }
        public string Symbol { get; set; }
        public string Description { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations { get; set; }
    }
}
