//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashBoardType()
        {
            this.DashBoardDetails = new HashSet<DashBoardDetail>();
            this.DashBoardRoles = new HashSet<DashBoardRole>();
        }
    
        public int DBTID { get; set; }
        public string DBTName { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> Priority { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int Created_By { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public bool IsStaticDashboardType { get; set; }
        public bool IsManagedByCMS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardDetail> DashBoardDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardRole> DashBoardRoles { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
