//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardRole
    {
        public int RoleID { get; set; }
        public int DBRoleID { get; set; }
        public int DBDTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual DashBoardType DashBoardType { get; set; }
        public virtual role role { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
