//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class dataentry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dataentry()
        {
            this.DataEntryRejectionHistories = new HashSet<DataEntryRejectionHistory>();
        }
    
        public int dataEntryID { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime workDate { get; set; }
        public int minutes { get; set; }
        public int workEventID { get; set; }
        public string workDesc { get; set; }
        public int empID { get; set; }
        public int projectID { get; set; }
        public Nullable<int> milestoneID { get; set; }
        public Nullable<int> taskID { get; set; }
        public Nullable<bool> IsHoliday { get; set; }
        public Nullable<bool> IsWorkFromHome { get; set; }
        public Nullable<int> WBSID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> OldWorkDate { get; set; }
        public Nullable<int> OldProjectID { get; set; }
        public Nullable<int> OldWBSID { get; set; }
        public Nullable<int> OldMinutes { get; set; }
        public Nullable<int> IsUpdated { get; set; }
        public Nullable<bool> IsBillableHours { get; set; }
        public Nullable<int> PercentageCompleted { get; set; }
        public Nullable<bool> IsClientMeeting { get; set; }
        public Nullable<bool> IsTraining { get; set; }
        public Nullable<bool> IsRejectedDataEntry { get; set; }
        public Nullable<bool> IsApprovedDataEntry { get; set; }
        public Nullable<bool> IsExternalTimesheet { get; set; }
        public Nullable<int> SprintId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual milestone milestone { get; set; }
        public virtual project project { get; set; }
        public virtual WB WB { get; set; }
        public virtual project project1 { get; set; }
        public virtual ProjectSprint ProjectSprint { get; set; }
        public virtual task task { get; set; }
        public virtual WB WB1 { get; set; }
        public virtual workevent workevent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataEntryRejectionHistory> DataEntryRejectionHistories { get; set; }
    }
}
