//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEntryRejectionHistory
    {
        public int DataEntryHistoryID { get; set; }
        public int DataEntryID { get; set; }
        public int EmpID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public int WorkMinutes { get; set; }
        public int WorkEventID { get; set; }
        public string WorkDesc { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> WBSID { get; set; }
        public string RejectionReason { get; set; }
        public System.DateTime RejectionDate { get; set; }
    
        public virtual dataentry dataentry { get; set; }
        public virtual employee employee { get; set; }
        public virtual project project { get; set; }
        public virtual WB WB { get; set; }
        public virtual workevent workevent { get; set; }
    }
}
