//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department()
        {
            this.AttendanceReportDepartmentLookups = new HashSet<AttendanceReportDepartmentLookup>();
            this.tblActionStepsforMeetings = new HashSet<tblActionStepsforMeeting>();
            this.employees = new HashSet<employee>();
            this.employeeReplicas = new HashSet<employeeReplica>();
            this.JobOffers = new HashSet<JobOffer>();
            this.projects = new HashSet<project>();
            this.projectinitiations = new HashSet<projectinitiation>();
            this.tblAttendanceExceptionDepartmentLookups = new HashSet<tblAttendanceExceptionDepartmentLookup>();
        }
    
        public int DeptID { get; set; }
        public string DeptName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IncrementPeriod { get; set; }
        public string DeptCode { get; set; }
        public Nullable<bool> IsMultipleShift { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public string LookedByEmp { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceReportDepartmentLookup> AttendanceReportDepartmentLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActionStepsforMeeting> tblActionStepsforMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeeReplica> employeeReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceExceptionDepartmentLookup> tblAttendanceExceptionDepartmentLookups { get; set; }
    }
}
