//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpADPasswordResetBlock
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public int NoOfAttempts { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> NextRetryDate { get; set; }
    }
}
