//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeSkill()
        {
            this.EmployeeSkillDetails = new HashSet<EmployeeSkillDetail>();
        }
    
        public int EmployeeSkillID { get; set; }
        public int empID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SkillFilledBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkillDetail> EmployeeSkillDetails { get; set; }
    }
}
