//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeedomainlookup
    {
        public int EmployeeDomainLookupId { get; set; }
        public int empID { get; set; }
        public int domainID { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employeedomainlookup employeedomainlookup1 { get; set; }
        public virtual employeedomainlookup employeedomainlookup2 { get; set; }
    }
}
