//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeColumnsReportMapping
    {
        public int EmpColMappingId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ColumnsId { get; set; }
        public Nullable<int> SortingOrderNo { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual ColumnsMaster ColumnsMaster { get; set; }
    }
}
