//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailReplica
    {
        public int EmployeeDetailReplicaID { get; set; }
        public int EmployeeDetailID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Name { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> DetailTypeID { get; set; }
        public Nullable<int> JobOfferId { get; set; }
        public Nullable<bool> IsRecordDeleted { get; set; }
        public Nullable<byte> ProfileStatus { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
