//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePLBalanceDetail
    {
        public int EmployeePLBalanceDetailsID { get; set; }
        public int EmpID { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<double> CurrentPLBalanace { get; set; }
        public Nullable<bool> IsPLBalanceInitialize { get; set; }
        public Nullable<bool> IsValidResignation { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<int> WeeklyHolidayTypeID { get; set; }
        public Nullable<double> CalculatedPLBalance { get; set; }
        public Nullable<double> DeductionDueToMismatchWfhTimesheetEntry { get; set; }
        public Nullable<double> DefaultPLBalance { get; set; }
        public Nullable<System.DateTime> EmployeeFinancialEndDate { get; set; }
        public Nullable<System.DateTime> EmployeeFinancialStartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public string FileName { get; set; }
        public Nullable<double> InitialPLBalance { get; set; }
        public Nullable<bool> IsAppicableForDefaultPLBalance { get; set; }
        public Nullable<bool> IsApplicableForPLtillRelievingdate { get; set; }
        public Nullable<bool> IsNewJoineeEmployee { get; set; }
        public Nullable<bool> IsNoticePeriodCalculationRequired { get; set; }
        public Nullable<double> PLDeduction { get; set; }
        public Nullable<double> PLDeductionForResignation { get; set; }
        public Nullable<double> PLIncrement { get; set; }
        public Nullable<double> TotalAbsent { get; set; }
        public Nullable<double> TotalAppliedPL { get; set; }
        public Nullable<double> TotalApprovedTour { get; set; }
        public Nullable<double> TotalApprovedWfh { get; set; }
        public Nullable<double> TotalRejectedPL { get; set; }
        public Nullable<double> TotalRejectedTour { get; set; }
        public Nullable<double> TotalSandwich { get; set; }
        public Nullable<double> wfhSandwichDeduction { get; set; }
        public Nullable<double> NewPLBalance { get; set; }
        public Nullable<double> PreviousBalance { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<bool> ResetPLBalance { get; set; }
        public Nullable<int> DayBeforeCalculatePLBalance { get; set; }
        public Nullable<int> AttendanceReportParameterId { get; set; }
    
        public virtual AttendanceReprotParameter AttendanceReprotParameter { get; set; }
        public virtual employee employee { get; set; }
        public virtual WeeklyHolidayType WeeklyHolidayType { get; set; }
    }
}
