//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorkingHoursTemp
    {
        public int empID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> WorkingHours { get; set; }
        public int EmployeeWorkingHourID { get; set; }
        public Nullable<System.DateTime> FirstInTime { get; set; }
        public Nullable<System.DateTime> LastOutTime { get; set; }
        public Nullable<decimal> TrainingSeminar { get; set; }
        public Nullable<decimal> ClientMeetingDemo { get; set; }
        public Nullable<decimal> WorkfromHome { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<int> ExceptionTypeId { get; set; }
        public Nullable<decimal> OldWorkingHours { get; set; }
        public Nullable<int> ExceptionID { get; set; }
        public Nullable<bool> IsAddedForException { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsPrimaryDateOfException { get; set; }
        public Nullable<bool> IsSecondaryOfException { get; set; }
        public string Status { get; set; }
        public bool IsMissPunch { get; set; }
        public Nullable<int> AttendanceType { get; set; }
        public Nullable<System.TimeSpan> WorkingHoursInTimeStamp { get; set; }
        public bool IsPunchFromMobile { get; set; }
    
        public virtual tblAttendanceException tblAttendanceException { get; set; }
    }
}
