//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.AppNotifications = new HashSet<AppNotification>();
            this.AppNotifications1 = new HashSet<AppNotification>();
            this.AttendanceReprotParameters = new HashSet<AttendanceReprotParameter>();
            this.AttendanceReprotParameters1 = new HashSet<AttendanceReprotParameter>();
            this.BankMasters = new HashSet<BankMaster>();
            this.BankMasters1 = new HashSet<BankMaster>();
            this.BUMasters = new HashSet<BUMaster>();
            this.companies = new HashSet<company>();
            this.companies1 = new HashSet<company>();
            this.ConferenceRoomMasters = new HashSet<ConferenceRoomMaster>();
            this.ConferenceRoomMasters1 = new HashSet<ConferenceRoomMaster>();
            this.DashBoardDetails = new HashSet<DashBoardDetail>();
            this.DashBoardDetails1 = new HashSet<DashBoardDetail>();
            this.DashBoardEmpLookUps = new HashSet<DashBoardEmpLookUp>();
            this.DashBoardEmpLookUps1 = new HashSet<DashBoardEmpLookUp>();
            this.DashBoardEmpLookUps2 = new HashSet<DashBoardEmpLookUp>();
            this.DashBoardRoles = new HashSet<DashBoardRole>();
            this.DashBoardRoles1 = new HashSet<DashBoardRole>();
            this.DashBoardTypes = new HashSet<DashBoardType>();
            this.DashBoardTypes1 = new HashSet<DashBoardType>();
            this.dataentries = new HashSet<dataentry>();
            this.DataEntryRejectionHistories = new HashSet<DataEntryRejectionHistory>();
            this.DocumentTypes = new HashSet<DocumentType>();
            this.DocumentTypes1 = new HashSet<DocumentType>();
            this.EmpGrossSalaries = new HashSet<EmpGrossSalary>();
            this.emphourlyavgs = new HashSet<emphourlyavg>();
            this.EmployeeColumnsReportMapping_NewReport = new HashSet<EmployeeColumnsReportMapping_NewReport>();
            this.tblActionStepsforMeetings = new HashSet<tblActionStepsforMeeting>();
            this.tblActionStepsforMeetings1 = new HashSet<tblActionStepsforMeeting>();
            this.tblProjectMeetingComments = new HashSet<tblProjectMeetingComment>();
            this.tblTaskComments = new HashSet<tblTaskComment>();
            this.employee1 = new HashSet<employee>();
            this.employee12 = new HashSet<employee>();
            this.employee13 = new HashSet<employee>();
            this.employee14 = new HashSet<employee>();
            this.EmployeeAttachments = new HashSet<EmployeeAttachment>();
            this.EmployeeCompetencyDetails = new HashSet<EmployeeCompetencyDetail>();
            this.EmployeeDetails = new HashSet<EmployeeDetail>();
            this.EmployeeDetailReplicas = new HashSet<EmployeeDetailReplica>();
            this.EmployeeDeviceMappings = new HashSet<EmployeeDeviceMapping>();
            this.employeedomainlookups = new HashSet<employeedomainlookup>();
            this.EmployeeDomainLookupReplicas = new HashSet<EmployeeDomainLookupReplica>();
            this.EmployeeEncashMasters = new HashSet<EmployeeEncashMaster>();
            this.EmployeeHistories = new HashSet<EmployeeHistory>();
            this.EmployeeHolidays = new HashSet<EmployeeHoliday>();
            this.EmployeeIncrements = new HashSet<EmployeeIncrement>();
            this.EmployeeInOutTemps = new HashSet<EmployeeInOutTemp>();
            this.EmployeeLanguageDetails = new HashSet<EmployeeLanguageDetail>();
            this.EmployeeLanguageDetailReplicas = new HashSet<EmployeeLanguageDetailReplica>();
            this.EmployeeLeaveMasters = new HashSet<EmployeeLeaveMaster>();
            this.EmployeeMarketingUpdateLookups = new HashSet<EmployeeMarketingUpdateLookup>();
            this.EmployeeModuleLookups = new HashSet<EmployeeModuleLookup>();
            this.EmployeePLBalanceDetails = new HashSet<EmployeePLBalanceDetail>();
            this.EmployeePreviousCompanies = new HashSet<EmployeePreviousCompany>();
            this.EmployeePreviousCompanyReplicas = new HashSet<EmployeePreviousCompanyReplica>();
            this.EmployeeQualifications = new HashSet<EmployeeQualification>();
            this.EmployeeQualificationReplicas = new HashSet<EmployeeQualificationReplica>();
            this.employeeReplicas = new HashSet<employeeReplica>();
            this.employeeReplicas1 = new HashSet<employeeReplica>();
            this.employeeReplicas2 = new HashSet<employeeReplica>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
            this.EmployeeSkills1 = new HashSet<EmployeeSkill>();
            this.EmployeeVisaDetails = new HashSet<EmployeeVisaDetail>();
            this.EmployeeVisaDetailReplicas = new HashSet<EmployeeVisaDetailReplica>();
            this.EvaluationNotes = new HashSet<EvaluationNote>();
            this.ExternalTrainerDetails = new HashSet<ExternalTrainerDetail>();
            this.ExternalTrainerDetails1 = new HashSet<ExternalTrainerDetail>();
            this.favoriteworkevents = new HashSet<favoriteworkevent>();
            this.HolidayEmployeeMappings = new HashSet<HolidayEmployeeMapping>();
            this.JobOffers = new HashSet<JobOffer>();
            this.JobOffers1 = new HashSet<JobOffer>();
            this.JobOffers2 = new HashSet<JobOffer>();
            this.JobOffers3 = new HashSet<JobOffer>();
            this.JobOffers4 = new HashSet<JobOffer>();
            this.LogTables = new HashSet<LogTable>();
            this.Lookups = new HashSet<Lookup>();
            this.Lookups1 = new HashSet<Lookup>();
            this.PenaltyEmployeeMappings = new HashSet<PenaltyEmployeeMapping>();
            this.PMSCustomScreens = new HashSet<PMSCustomScreen>();
            this.PMSCustomScreens1 = new HashSet<PMSCustomScreen>();
            this.PMSEvents = new HashSet<PMSEvent>();
            this.PMSEvents1 = new HashSet<PMSEvent>();
            this.PMSEventTypes = new HashSet<PMSEventType>();
            this.PMSEventTypes1 = new HashSet<PMSEventType>();
            this.PMSReleases = new HashSet<PMSRelease>();
            this.PMSReleases1 = new HashSet<PMSRelease>();
            this.PMSWorkflows = new HashSet<PMSWorkflow>();
            this.PMSWorkflows1 = new HashSet<PMSWorkflow>();
            this.PMSWorkflowTransitions = new HashSet<PMSWorkflowTransition>();
            this.PMSWorkflowTransitions1 = new HashSet<PMSWorkflowTransition>();
            this.PMSWorkflowTransitionDatas = new HashSet<PMSWorkflowTransitionData>();
            this.projects = new HashSet<project>();
            this.projects1 = new HashSet<project>();
            this.projects2 = new HashSet<project>();
            this.ProjectConfigMappings = new HashSet<ProjectConfigMapping>();
            this.ProjectConfigMappings1 = new HashSet<ProjectConfigMapping>();
            this.projectinitiations = new HashSet<projectinitiation>();
            this.projectinitiations1 = new HashSet<projectinitiation>();
            this.projectinitiations2 = new HashSet<projectinitiation>();
            this.projectinitiations3 = new HashSet<projectinitiation>();
            this.projectinitiations4 = new HashSet<projectinitiation>();
            this.projectinitiations5 = new HashSet<projectinitiation>();
            this.projectinitiations6 = new HashSet<projectinitiation>();
            this.projectinitiations7 = new HashSet<projectinitiation>();
            this.projectinitiations8 = new HashSet<projectinitiation>();
            this.ProjectInitiationPaymentMilestones = new HashSet<ProjectInitiationPaymentMilestone>();
            this.ProjectInitiationPaymentMilestones1 = new HashSet<ProjectInitiationPaymentMilestone>();
            this.ProjectInitiationResources = new HashSet<ProjectInitiationResource>();
            this.ProjectInitiationResources1 = new HashSet<ProjectInitiationResource>();
            this.ProjectInitiationResourcesHistories = new HashSet<ProjectInitiationResourcesHistory>();
            this.ProjectSprints = new HashSet<ProjectSprint>();
            this.ProjectSprints1 = new HashSet<ProjectSprint>();
            this.Receipts = new HashSet<Receipt>();
            this.Receipts1 = new HashSet<Receipt>();
            this.tblActivityDetails = new HashSet<tblActivityDetail>();
            this.tblActivityDetails1 = new HashSet<tblActivityDetail>();
            this.tblAttendanceExceptions = new HashSet<tblAttendanceException>();
            this.tblAttendanceExceptions1 = new HashSet<tblAttendanceException>();
            this.tblAttendanceExceptionDepartmentLookups = new HashSet<tblAttendanceExceptionDepartmentLookup>();
            this.tblAttendanceExceptionDepartmentLookups1 = new HashSet<tblAttendanceExceptionDepartmentLookup>();
            this.tblAttendanceExceptionEmployeeLookups = new HashSet<tblAttendanceExceptionEmployeeLookup>();
            this.tblAttendanceExceptionEmployeeLookups1 = new HashSet<tblAttendanceExceptionEmployeeLookup>();
            this.tblAttendanceExceptionEmployeeLookups2 = new HashSet<tblAttendanceExceptionEmployeeLookup>();
            this.tblAttendanceReportPLBalances = new HashSet<tblAttendanceReportPLBalance>();
            this.tblBranches = new HashSet<tblBranch>();
            this.tblBranches1 = new HashSet<tblBranch>();
            this.tblCIMSBackgroundImages = new HashSet<tblCIMSBackgroundImage>();
            this.tblCIMSBackgroundImages1 = new HashSet<tblCIMSBackgroundImage>();
            this.tblCompetencyRatings = new HashSet<tblCompetencyRating>();
            this.tblCompetencyRatings1 = new HashSet<tblCompetencyRating>();
            this.tblKRADevelopmentPlans = new HashSet<tblKRADevelopmentPlan>();
            this.tblKPIs = new HashSet<tblKPI>();
            this.tblEmployeeReferralBonus = new HashSet<tblEmployeeReferralBonu>();
            this.tblEmployeeReferralBonus1 = new HashSet<tblEmployeeReferralBonu>();
            this.tblEmployeeReferralBonus2 = new HashSet<tblEmployeeReferralBonu>();
            this.tblEmployeeReferralBonus3 = new HashSet<tblEmployeeReferralBonu>();
            this.tblEmployeeSchedules = new HashSet<tblEmployeeSchedule>();
            this.tblEmployeeWbsLookups = new HashSet<tblEmployeeWbsLookup>();
            this.tblEmpPasswordTracks = new HashSet<tblEmpPasswordTrack>();
            this.tblEvaluationComments = new HashSet<tblEvaluationComment>();
            this.tblEvalutionParams = new HashSet<tblEvalutionParam>();
            this.tblEvalutionParams1 = new HashSet<tblEvalutionParam>();
            this.tblExternalTaskTimesheetImportMappings = new HashSet<tblExternalTaskTimesheetImportMapping>();
            this.tblIterationHistories = new HashSet<tblIterationHistory>();
            this.tblJustifications = new HashSet<tblJustification>();
            this.tblJustifications1 = new HashSet<tblJustification>();
            this.tblKPIs1 = new HashSet<tblKPI>();
            this.tblKRAAssigns = new HashSet<tblKRAAssign>();
            this.tblKRAAssigns1 = new HashSet<tblKRAAssign>();
            this.tblKRAAssigns2 = new HashSet<tblKRAAssign>();
            this.tblKRAAssignDetails = new HashSet<tblKRAAssignDetail>();
            this.tblKRAAssignDetails1 = new HashSet<tblKRAAssignDetail>();
            this.tblKRAEVLPRM_Relation = new HashSet<tblKRAEVLPRM_Relation>();
            this.tblKRAKPI_Relation = new HashSet<tblKRAKPI_Relation>();
            this.tblKRATempDetails = new HashSet<tblKRATempDetail>();
            this.tblKRATempDetails1 = new HashSet<tblKRATempDetail>();
            this.tblKRATemplates = new HashSet<tblKRATemplate>();
            this.tblKRATemplates1 = new HashSet<tblKRATemplate>();
            this.tblLinks = new HashSet<tblLink>();
            this.tblLinks1 = new HashSet<tblLink>();
            this.tblLocations = new HashSet<tblLocation>();
            this.tblLocations1 = new HashSet<tblLocation>();
            this.tblNotifications = new HashSet<tblNotification>();
            this.tblNotificationUsers = new HashSet<tblNotificationUser>();
            this.tblObjectives = new HashSet<tblObjective>();
            this.tblObjectives1 = new HashSet<tblObjective>();
            this.tblOrgBandMasters = new HashSet<tblOrgBandMaster>();
            this.tblOrgBandMasters1 = new HashSet<tblOrgBandMaster>();
            this.tblOrgLevelBandTiersLookups = new HashSet<tblOrgLevelBandTiersLookup>();
            this.tblOrgLevelBandTiersLookups1 = new HashSet<tblOrgLevelBandTiersLookup>();
            this.tblOrgLevelMasters = new HashSet<tblOrgLevelMaster>();
            this.tblOrgLevelMasters1 = new HashSet<tblOrgLevelMaster>();
            this.tblOrgTiersMasters = new HashSet<tblOrgTiersMaster>();
            this.tblOrgTiersMasters1 = new HashSet<tblOrgTiersMaster>();
            this.tblProcesses = new HashSet<tblProcess>();
            this.tblProfileRejectionHistories = new HashSet<tblProfileRejectionHistory>();
            this.tblProfileRejectionHistories1 = new HashSet<tblProfileRejectionHistory>();
            this.tblProfileRejectionHistories2 = new HashSet<tblProfileRejectionHistory>();
            this.tblProjectInitiationLookups = new HashSet<tblProjectInitiationLookup>();
            this.tblProjectStatusQuestions = new HashSet<tblProjectStatusQuestion>();
            this.tblQuestionCategories = new HashSet<tblQuestionCategory>();
            this.tblQuestionCategories1 = new HashSet<tblQuestionCategory>();
            this.TblRequestFieldMasters = new HashSet<TblRequestFieldMaster>();
            this.TblRequestFieldMasters1 = new HashSet<TblRequestFieldMaster>();
            this.tblSetTemplates = new HashSet<tblSetTemplate>();
            this.tblSetTemplates1 = new HashSet<tblSetTemplate>();
            this.tblSkillRatings = new HashSet<tblSkillRating>();
            this.tblSkillRatings1 = new HashSet<tblSkillRating>();
            this.tblSuggestions = new HashSet<tblSuggestion>();
            this.tblSuggestions1 = new HashSet<tblSuggestion>();
            this.tblTaskRemainingHourDetails = new HashSet<tblTaskRemainingHourDetail>();
            this.tblTaskRemainingHourDetails1 = new HashSet<tblTaskRemainingHourDetail>();
            this.tblTaskStatus = new HashSet<tblTaskStatu>();
            this.tblTaskStatus1 = new HashSet<tblTaskStatu>();
            this.tblTrainingFeedBackAnswers = new HashSet<tblTrainingFeedBackAnswer>();
            this.tblTrainingFeedBackMasters = new HashSet<tblTrainingFeedBackMaster>();
            this.tblTrainingFeedBackMasters1 = new HashSet<tblTrainingFeedBackMaster>();
            this.tblTrainingFeedBackMasters2 = new HashSet<tblTrainingFeedBackMaster>();
            this.tblTrainingFeedbackQuestions = new HashSet<tblTrainingFeedbackQuestion>();
            this.tblTrainingFeedbackQuestions1 = new HashSet<tblTrainingFeedbackQuestion>();
            this.tblTrainingNominations = new HashSet<tblTrainingNomination>();
            this.tblTrainingNominations1 = new HashSet<tblTrainingNomination>();
            this.tblTrainingNominations2 = new HashSet<tblTrainingNomination>();
            this.tblTrainingWaiverDetails = new HashSet<tblTrainingWaiverDetail>();
            this.tblTrainingWaiverMasters = new HashSet<tblTrainingWaiverMaster>();
            this.tblTrainingWaiverMasters1 = new HashSet<tblTrainingWaiverMaster>();
            this.tblTrainingWaiverMasters2 = new HashSet<tblTrainingWaiverMaster>();
            this.TeamMembers = new HashSet<TeamMember>();
            this.Templates = new HashSet<Template>();
            this.Templates1 = new HashSet<Template>();
            this.timeoffrequests = new HashSet<timeoffrequest>();
            this.timeoffrequests1 = new HashSet<timeoffrequest>();
            this.timeoffrequests2 = new HashSet<timeoffrequest>();
            this.timeoffrequests3 = new HashSet<timeoffrequest>();
            this.TimesheetConfigurations = new HashSet<TimesheetConfiguration>();
            this.TimesheetConfigurations1 = new HashSet<TimesheetConfiguration>();
            this.TimesheetConfigurations2 = new HashSet<TimesheetConfiguration>();
            this.TraineeDetails = new HashSet<TraineeDetail>();
            this.TrainerDetails = new HashSet<TrainerDetail>();
            this.TrainingCategories = new HashSet<TrainingCategory>();
            this.TrainingCategories1 = new HashSet<TrainingCategory>();
            this.TrainingDetails = new HashSet<TrainingDetail>();
            this.TrainingDetails1 = new HashSet<TrainingDetail>();
            this.TrainingEmployeeLogs = new HashSet<TrainingEmployeeLog>();
            this.TrainingEvaluations = new HashSet<TrainingEvaluation>();
            this.TrainingEvaluations1 = new HashSet<TrainingEvaluation>();
            this.TrainingMasters = new HashSet<TrainingMaster>();
            this.TrainingMasters1 = new HashSet<TrainingMaster>();
            this.TrainingObjectives = new HashSet<TrainingObjective>();
            this.TrainingObjectives1 = new HashSet<TrainingObjective>();
            this.WBS = new HashSet<WB>();
            this.WBS1 = new HashSet<WB>();
            this.WBSEmpLinks = new HashSet<WBSEmpLink>();
            this.WBSVersionHistories = new HashSet<WBSVersionHistory>();
            this.WBSVersionHistories1 = new HashSet<WBSVersionHistory>();
            this.WorkItemMasters = new HashSet<WorkItemMaster>();
            this.WorkItemMasters1 = new HashSet<WorkItemMaster>();
        }
    
        public int empID { get; set; }
        public string empCode { get; set; }
        public string loginID { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public string bloodGroup { get; set; }
        public Nullable<bool> active { get; set; }
        public string sex { get; set; }
        public System.DateTime birthDate { get; set; }
        public System.DateTime joinDate { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string pin { get; set; }
        public string email { get; set; }
        public string personalEmail { get; set; }
        public string cellNo { get; set; }
        public string homeNo { get; set; }
        public string bankAccountID { get; set; }
        public string vehicaleNo { get; set; }
        public string passportNo { get; set; }
        public int roleID { get; set; }
        public Nullable<int> pmID { get; set; }
        public int employeeStatusID { get; set; }
        public string GDegree { get; set; }
        public string GSpecialization { get; set; }
        public string GYear { get; set; }
        public string PGDegree { get; set; }
        public string PGSpecialization { get; set; }
        public string PGYear { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CareerStartDate { get; set; }
        public Nullable<int> MonthGapsInCareer { get; set; }
        public Nullable<decimal> ReqAvgWorkingHours { get; set; }
        public int DepartmentID { get; set; }
        public bool IsReportingManager { get; set; }
        public bool IsApprovalRequired { get; set; }
        public bool HaveReportingManager { get; set; }
        public Nullable<int> PrivilegeRoleID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsTimesheetMandatory { get; set; }
        public string OtherNo { get; set; }
        public Nullable<decimal> Utilization { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> WeeklyHolidayTypeID { get; set; }
        public Nullable<System.DateTime> LastIncrementDate { get; set; }
        public Nullable<int> IncrementPeriod { get; set; }
        public string EmpResume { get; set; }
        public string Extension { get; set; }
        public byte[] ResumeData { get; set; }
        public string ResumeText { get; set; }
        public string Contenttype { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string GrossSalary { get; set; }
        public string PFNumber { get; set; }
        public string ESINumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpouseOccupation { get; set; }
        public Nullable<System.DateTime> SpouseDOB { get; set; }
        public Nullable<System.DateTime> resignDate { get; set; }
        public string EmployeePhoto { get; set; }
        public Nullable<int> DefaultProjectId { get; set; }
        public int IsDelete { get; set; }
        public Nullable<bool> IsMigrationRequired { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public string panNo { get; set; }
        public Nullable<System.DateTime> ProbationDate { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public string RegReason { get; set; }
        public Nullable<int> OldEmpID { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<double> CurrentPLBalance { get; set; }
        public Nullable<decimal> InitialPLBalance { get; set; }
        public Nullable<bool> IsPLBalanceInitialize { get; set; }
        public Nullable<bool> IsNoticePeriodServed { get; set; }
        public Nullable<int> IsProfileApproved { get; set; }
        public Nullable<bool> IsActiveWishesAlert { get; set; }
        public Nullable<int> StayedMonthsAtPermanentAddress { get; set; }
        public string FatherContNo { get; set; }
        public string MotherContNo { get; set; }
        public string SpouseContNo { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentPin { get; set; }
        public Nullable<int> StayedMonthsAtPresentAddress { get; set; }
        public string VisaNotes { get; set; }
        public Nullable<bool> IsLocalAndPermanentAddressSame { get; set; }
        public Nullable<bool> IsMarketingUpdateRead { get; set; }
        public Nullable<bool> IsInternalTrainer { get; set; }
        public Nullable<System.DateTime> FatherBirthDate { get; set; }
        public Nullable<System.DateTime> MotherBirthDate { get; set; }
        public bool IsFatherLate { get; set; }
        public bool IsMotherLate { get; set; }
        public Nullable<int> SpouseTitle { get; set; }
        public Nullable<int> Citizenship { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string LDAPUserName { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string ReportingManagerEmpCode { get; set; }
        public string EmployeeStatusName { get; set; }
        public Nullable<int> MyProfileStatus { get; set; }
        public string MyProfileRejectReason { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public bool isFromOutstation { get; set; }
        public Nullable<System.DateTime> PFJoinDate { get; set; }
        public Nullable<long> UANNumber { get; set; }
        public Nullable<int> PTNumber { get; set; }
        public Nullable<long> AadharCardNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<long> VPF { get; set; }
        public Nullable<int> SalaryTypeId { get; set; }
        public bool IsPFDeduct { get; set; }
        public bool IsPTDeduct { get; set; }
        public bool IsHRADeduct { get; set; }
        public string PayrollRemarks { get; set; }
        public bool IsESICDeduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppNotification> AppNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppNotification> AppNotifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceReprotParameter> AttendanceReprotParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceReprotParameter> AttendanceReprotParameters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankMaster> BankMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankMaster> BankMasters1 { get; set; }
        public virtual BankMaster BankMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUMaster> BUMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company> companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company> companies1 { get; set; }
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceRoomMaster> ConferenceRoomMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceRoomMaster> ConferenceRoomMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardDetail> DashBoardDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardDetail> DashBoardDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardEmpLookUp> DashBoardEmpLookUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardEmpLookUp> DashBoardEmpLookUps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardEmpLookUp> DashBoardEmpLookUps2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardRole> DashBoardRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardRole> DashBoardRoles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardType> DashBoardTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardType> DashBoardTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataentry> dataentries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataEntryRejectionHistory> DataEntryRejectionHistories { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentType> DocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentType> DocumentTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpGrossSalary> EmpGrossSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emphourlyavg> emphourlyavgs { get; set; }
        public virtual Policy Policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeColumnsReportMapping_NewReport> EmployeeColumnsReportMapping_NewReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActionStepsforMeeting> tblActionStepsforMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActionStepsforMeeting> tblActionStepsforMeetings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectMeetingComment> tblProjectMeetingComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskComment> tblTaskComments { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual project project { get; set; }
        public virtual employee employee11 { get; set; }
        public virtual employee employee3 { get; set; }
        public virtual employeestatu employeestatu { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee12 { get; set; }
        public virtual employee employee4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee13 { get; set; }
        public virtual employee employee5 { get; set; }
        public virtual PrivilegeRole PrivilegeRole { get; set; }
        public virtual role role { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual tblOrgLevelMaster tblOrgLevelMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee14 { get; set; }
        public virtual employee employee6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAttachment> EmployeeAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCompetencyDetail> EmployeeCompetencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDetail> EmployeeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDetailReplica> EmployeeDetailReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDeviceMapping> EmployeeDeviceMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeedomainlookup> employeedomainlookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDomainLookupReplica> EmployeeDomainLookupReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEncashMaster> EmployeeEncashMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeHistory> EmployeeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeHoliday> EmployeeHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeIncrement> EmployeeIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeInOutTemp> EmployeeInOutTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLanguageDetail> EmployeeLanguageDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLanguageDetailReplica> EmployeeLanguageDetailReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeaveMaster> EmployeeLeaveMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeMarketingUpdateLookup> EmployeeMarketingUpdateLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeModuleLookup> EmployeeModuleLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePLBalanceDetail> EmployeePLBalanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePreviousCompany> EmployeePreviousCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePreviousCompanyReplica> EmployeePreviousCompanyReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeQualification> EmployeeQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeQualificationReplica> EmployeeQualificationReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeeReplica> employeeReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeeReplica> employeeReplicas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employeeReplica> employeeReplicas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkill> EmployeeSkills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVisaDetail> EmployeeVisaDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeVisaDetailReplica> EmployeeVisaDetailReplicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationNote> EvaluationNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalTrainerDetail> ExternalTrainerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalTrainerDetail> ExternalTrainerDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favoriteworkevent> favoriteworkevents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HolidayEmployeeMapping> HolidayEmployeeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOffer> JobOffers4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTable> LogTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lookup> Lookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lookup> Lookups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PenaltyEmployeeMapping> PenaltyEmployeeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSCustomScreen> PMSCustomScreens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSCustomScreen> PMSCustomScreens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSEvent> PMSEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSEvent> PMSEvents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSEventType> PMSEventTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSEventType> PMSEventTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSRelease> PMSReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSRelease> PMSReleases1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflow> PMSWorkflows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflow> PMSWorkflows1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransition> PMSWorkflowTransitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransition> PMSWorkflowTransitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransitionData> PMSWorkflowTransitionDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectConfigMapping> ProjectConfigMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectConfigMapping> ProjectConfigMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projectinitiation> projectinitiations8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationPaymentMilestone> ProjectInitiationPaymentMilestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationPaymentMilestone> ProjectInitiationPaymentMilestones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResource> ProjectInitiationResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResource> ProjectInitiationResources1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResourcesHistory> ProjectInitiationResourcesHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSprint> ProjectSprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSprint> ProjectSprints1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivityDetail> tblActivityDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivityDetail> tblActivityDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceException> tblAttendanceExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceException> tblAttendanceExceptions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceExceptionDepartmentLookup> tblAttendanceExceptionDepartmentLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceExceptionDepartmentLookup> tblAttendanceExceptionDepartmentLookups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceExceptionEmployeeLookup> tblAttendanceExceptionEmployeeLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceExceptionEmployeeLookup> tblAttendanceExceptionEmployeeLookups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceExceptionEmployeeLookup> tblAttendanceExceptionEmployeeLookups2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendanceReportPLBalance> tblAttendanceReportPLBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBranch> tblBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBranch> tblBranches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCIMSBackgroundImage> tblCIMSBackgroundImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCIMSBackgroundImage> tblCIMSBackgroundImages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompetencyRating> tblCompetencyRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompetencyRating> tblCompetencyRatings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRADevelopmentPlan> tblKRADevelopmentPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKPI> tblKPIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeReferralBonu> tblEmployeeReferralBonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeReferralBonu> tblEmployeeReferralBonus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeReferralBonu> tblEmployeeReferralBonus2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeReferralBonu> tblEmployeeReferralBonus3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeSchedule> tblEmployeeSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeWbsLookup> tblEmployeeWbsLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpPasswordTrack> tblEmpPasswordTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvaluationComment> tblEvaluationComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvalutionParam> tblEvalutionParams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvalutionParam> tblEvalutionParams1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExternalTaskTimesheetImportMapping> tblExternalTaskTimesheetImportMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIterationHistory> tblIterationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJustification> tblJustifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJustification> tblJustifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKPI> tblKPIs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssign> tblKRAAssigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssign> tblKRAAssigns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssign> tblKRAAssigns2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssignDetail> tblKRAAssignDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssignDetail> tblKRAAssignDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAEVLPRM_Relation> tblKRAEVLPRM_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAKPI_Relation> tblKRAKPI_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRATempDetail> tblKRATempDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRATempDetail> tblKRATempDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRATemplate> tblKRATemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRATemplate> tblKRATemplates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLink> tblLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLink> tblLinks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocation> tblLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocation> tblLocations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotificationUser> tblNotificationUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblObjective> tblObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblObjective> tblObjectives1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgBandMaster> tblOrgBandMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgBandMaster> tblOrgBandMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgLevelBandTiersLookup> tblOrgLevelBandTiersLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgLevelBandTiersLookup> tblOrgLevelBandTiersLookups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgLevelMaster> tblOrgLevelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgLevelMaster> tblOrgLevelMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgTiersMaster> tblOrgTiersMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrgTiersMaster> tblOrgTiersMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProcess> tblProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfileRejectionHistory> tblProfileRejectionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfileRejectionHistory> tblProfileRejectionHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfileRejectionHistory> tblProfileRejectionHistories2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectInitiationLookup> tblProjectInitiationLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectStatusQuestion> tblProjectStatusQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestionCategory> tblQuestionCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestionCategory> tblQuestionCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRequestFieldMaster> TblRequestFieldMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRequestFieldMaster> TblRequestFieldMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSetTemplate> tblSetTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSetTemplate> tblSetTemplates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSkillRating> tblSkillRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSkillRating> tblSkillRatings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestion> tblSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuggestion> tblSuggestions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskRemainingHourDetail> tblTaskRemainingHourDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskRemainingHourDetail> tblTaskRemainingHourDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskStatu> tblTaskStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskStatu> tblTaskStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedBackAnswer> tblTrainingFeedBackAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedBackMaster> tblTrainingFeedBackMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedBackMaster> tblTrainingFeedBackMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedBackMaster> tblTrainingFeedBackMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedbackQuestion> tblTrainingFeedbackQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedbackQuestion> tblTrainingFeedbackQuestions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingNomination> tblTrainingNominations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingNomination> tblTrainingNominations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingNomination> tblTrainingNominations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingWaiverDetail> tblTrainingWaiverDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingWaiverMaster> tblTrainingWaiverMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingWaiverMaster> tblTrainingWaiverMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingWaiverMaster> tblTrainingWaiverMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template> Templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template> Templates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeoffrequest> timeoffrequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeoffrequest> timeoffrequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeoffrequest> timeoffrequests2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeoffrequest> timeoffrequests3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetConfiguration> TimesheetConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetConfiguration> TimesheetConfigurations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetConfiguration> TimesheetConfigurations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeDetail> TraineeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerDetail> TrainerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingCategory> TrainingCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingCategory> TrainingCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingDetail> TrainingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingDetail> TrainingDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingEmployeeLog> TrainingEmployeeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingEvaluation> TrainingEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingEvaluation> TrainingEvaluations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingMaster> TrainingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingMaster> TrainingMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingObjective> TrainingObjectives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingObjective> TrainingObjectives1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WB> WBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WB> WBS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBSEmpLink> WBSEmpLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBSVersionHistory> WBSVersionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBSVersionHistory> WBSVersionHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemMaster> WorkItemMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemMaster> WorkItemMasters1 { get; set; }
    }
}
