//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIncrement
    {
        public int EmpIncrementID { get; set; }
        public int empID { get; set; }
        public string Employee { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public string Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsLastEffectiveDateAffected { get; set; }
        public bool Isdelete { get; set; }
    
        public virtual employee employee1 { get; set; }
    }
}
