//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeReplica
    {
        public int EmpReplicaID { get; set; }
        public int empID { get; set; }
        public string empCode { get; set; }
        public string loginID { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public string bloodGroup { get; set; }
        public Nullable<bool> active { get; set; }
        public string sex { get; set; }
        public System.DateTime birthDate { get; set; }
        public System.DateTime joinDate { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string pin { get; set; }
        public string email { get; set; }
        public string personalEmail { get; set; }
        public string cellNo { get; set; }
        public string homeNo { get; set; }
        public string bankAccountID { get; set; }
        public string vehicaleNo { get; set; }
        public string passportNo { get; set; }
        public int roleID { get; set; }
        public Nullable<int> pmID { get; set; }
        public int employeeStatusID { get; set; }
        public string GDegree { get; set; }
        public string GSpecialization { get; set; }
        public string GYear { get; set; }
        public string PGDegree { get; set; }
        public string PGSpecialization { get; set; }
        public string PGYear { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CareerStartDate { get; set; }
        public Nullable<int> MonthGapsInCareer { get; set; }
        public Nullable<decimal> ReqAvgWorkingHours { get; set; }
        public int DepartmentID { get; set; }
        public bool IsReportingManager { get; set; }
        public bool IsApprovalRequired { get; set; }
        public bool HaveReportingManager { get; set; }
        public Nullable<int> PrivilegeRoleID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsTimesheetMandatory { get; set; }
        public string OtherNo { get; set; }
        public Nullable<decimal> Utilization { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> WeeklyHolidayTypeID { get; set; }
        public Nullable<System.DateTime> LastIncrementDate { get; set; }
        public Nullable<int> IncrementPeriod { get; set; }
        public string EmpResume { get; set; }
        public string Extension { get; set; }
        public byte[] ResumeData { get; set; }
        public string ResumeText { get; set; }
        public string Contenttype { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string GrossSalary { get; set; }
        public string PFNumber { get; set; }
        public string ESINumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpouseOccupation { get; set; }
        public Nullable<System.DateTime> SpouseDOB { get; set; }
        public Nullable<System.DateTime> resignDate { get; set; }
        public string EmployeePhoto { get; set; }
        public int DefaultProjectId { get; set; }
        public int IsDelete { get; set; }
        public string panNo { get; set; }
        public Nullable<int> OldEmpID { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public Nullable<System.DateTime> confirmationDate { get; set; }
        public Nullable<System.DateTime> ProbationDate { get; set; }
        public string RegReason { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string VisaNotes { get; set; }
        public Nullable<int> StayedMonthsAtPresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentPin { get; set; }
        public Nullable<int> StayedMonthsAtPermanentAddress { get; set; }
        public Nullable<int> IsProfileApproved { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> IsMigrationRequired { get; set; }
        public Nullable<bool> IsPLBalanceInitialize { get; set; }
        public Nullable<decimal> InitialPLBalance { get; set; }
        public Nullable<double> CurrentPLBalance { get; set; }
        public string FatherContNo { get; set; }
        public string MotherContNo { get; set; }
        public string SpouseContNo { get; set; }
        public Nullable<bool> IsActiveWishesAlert { get; set; }
        public Nullable<bool> IsNoticePeriodServed { get; set; }
        public Nullable<bool> IsLocalAndPermanentAddressSame { get; set; }
        public Nullable<bool> IsInternalTrainer { get; set; }
        public Nullable<bool> IsMarketingUpdateRead { get; set; }
        public Nullable<System.DateTime> FatherBirthDate { get; set; }
        public Nullable<System.DateTime> MotherBirthDate { get; set; }
        public bool IsFatherLate { get; set; }
        public bool IsMotherLate { get; set; }
        public Nullable<int> SpouseTitle { get; set; }
        public Nullable<int> Citizenship { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string RejectReason { get; set; }
        public Nullable<int> ProfileStatus { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public bool isFromOutstation { get; set; }
        public Nullable<System.DateTime> PFJoinDate { get; set; }
        public Nullable<long> UANNumber { get; set; }
        public Nullable<int> PTNumber { get; set; }
        public Nullable<long> AadharCardNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<long> VPF { get; set; }
        public Nullable<int> SalaryTypeId { get; set; }
        public bool IsPFDeduct { get; set; }
        public bool IsPTDeduct { get; set; }
        public bool IsHRADeduct { get; set; }
        public string PayrollRemarks { get; set; }
        public bool IsESICDeduct { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
        public virtual company company { get; set; }
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual tblOrgLevelMaster tblOrgLevelMaster { get; set; }
        public virtual WeeklyHolidayType WeeklyHolidayType { get; set; }
    }
}
