//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationNote
    {
        public int EvaluationNoteId { get; set; }
        public int KRAEvalId { get; set; }
        public int TeamMemberKRAId { get; set; }
        public int EvaluationNoteType { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rating { get; set; }
        public int Created_By { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual KRAEvaluation KRAEvaluation { get; set; }
        public virtual TeamMembersKRA TeamMembersKRA { get; set; }
    }
}
