//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactAnalysi
    {
        public int ImpactAnalysisID { get; set; }
        public Nullable<int> ChangeRequestID { get; set; }
        public string WorkProduct { get; set; }
        public string NextVersion { get; set; }
        public string SectionNo { get; set; }
        public string ResponsibilityForChange { get; set; }
        public string ActualCompletionDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
