//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices_Project()
        {
            this.Invoice_HourlyPayment = new HashSet<Invoice_HourlyPayment>();
        }
    
        public int InvoiceID { get; set; }
        public Nullable<int> projectID { get; set; }
        public string PaymentMileStone { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public Nullable<bool> IsPaymentMileStoneAchieved { get; set; }
        public Nullable<System.DateTime> PaymentMileStoneAchievedDate { get; set; }
        public Nullable<bool> IsInvoiceRaised { get; set; }
        public Nullable<System.DateTime> InvoiceRaisedDate { get; set; }
        public Nullable<bool> IsPaymentReceived { get; set; }
        public Nullable<System.DateTime> PaymentReceivedDate { get; set; }
        public Nullable<System.DateTime> LastEmailDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Recurrence { get; set; }
        public string Day { get; set; }
        public Nullable<bool> IsFirstEmail { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_HourlyPayment> Invoice_HourlyPayment { get; set; }
        public virtual project project { get; set; }
    }
}
