//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOffer()
        {
            this.EmployeeDetails = new HashSet<EmployeeDetail>();
        }
    
        public int empID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public Nullable<bool> active { get; set; }
        public string sex { get; set; }
        public System.DateTime joinDate { get; set; }
        public string personalEmail { get; set; }
        public string cellNo { get; set; }
        public int roleID { get; set; }
        public Nullable<int> pmID { get; set; }
        public int employeeStatusID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> companyID { get; set; }
        public string EmpResume { get; set; }
        public int IsDelete { get; set; }
        public int hasJoined { get; set; }
        public string Remarks { get; set; }
        public string ResumeText { get; set; }
        public string Extension { get; set; }
        public Nullable<int> WeeklyHolidaytypeID { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public string DenyJoiningReason { get; set; }
        public Nullable<int> RecruiterID { get; set; }
        public Nullable<System.DateTime> DenyDate { get; set; }
        public Nullable<int> ReferralEmpId { get; set; }
        public Nullable<int> MonthGapsInCareer { get; set; }
        public Nullable<System.DateTime> CareerStartDate { get; set; }
        public string EmployeePhoto { get; set; }
        public string EmployeeIDProof { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual company company { get; set; }
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual employee employee3 { get; set; }
        public virtual employee employee4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual employeestatu employeestatu { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual role role { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
