//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveBalanceMaster
    {
        public int lvbalId { get; set; }
        public int empid { get; set; }
        public Nullable<double> openBalancePL { get; set; }
        public Nullable<double> closeBalancePL { get; set; }
        public Nullable<double> openBalanceSL { get; set; }
        public Nullable<double> closeBalanceSL { get; set; }
        public Nullable<int> lvcode { get; set; }
    }
}
