//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixDeviceInfoMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatrixDeviceInfoMaster()
        {
            this.MatrixDeviceInfoDetails = new HashSet<MatrixDeviceInfoDetail>();
            this.MatrixDeviceInfoDetails1 = new HashSet<MatrixDeviceInfoDetail>();
            this.MatrixInterOfficePunches = new HashSet<MatrixInterOfficePunch>();
            this.MatrixInterOfficePunches1 = new HashSet<MatrixInterOfficePunch>();
        }
    
        public int ID { get; set; }
        public int MID { get; set; }
        public string NodeName { get; set; }
        public string DoorName { get; set; }
        public bool IsAttendance { get; set; }
        public int DType { get; set; }
        public bool IsActive { get; set; }
        public string BranchName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixDeviceInfoDetail> MatrixDeviceInfoDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixDeviceInfoDetail> MatrixDeviceInfoDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixInterOfficePunch> MatrixInterOfficePunches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixInterOfficePunch> MatrixInterOfficePunches1 { get; set; }
    }
}
