//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixInterOfficePunch
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public string EmpCode { get; set; }
        public System.DateTime PunchDate { get; set; }
        public System.DateTime OutTime { get; set; }
        public string OutPunchOffice { get; set; }
        public System.DateTime InTime { get; set; }
        public string InPunchOffice { get; set; }
        public decimal Seconds { get; set; }
        public decimal MaxAllowSeconds { get; set; }
        public decimal SecondsConsider { get; set; }
        public int InMatrixInfoID { get; set; }
        public int OutMatrixInfoID { get; set; }
        public string OutDoorName { get; set; }
        public string InDoorName { get; set; }
    
        public virtual MatrixDeviceInfoMaster MatrixDeviceInfoMaster { get; set; }
        public virtual MatrixDeviceInfoMaster MatrixDeviceInfoMaster1 { get; set; }
    }
}
