//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Missmatch
    {
        public Nullable<int> Employee_Id { get; set; }
        public string Employee_Name_ { get; set; }
        public string Leave_Group { get; set; }
        public Nullable<System.DateTime> Attendance_date { get; set; }
        public Nullable<System.DateTime> Time_Sheet_Entry_date { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Till_Date { get; set; }
        public Nullable<decimal> Total_Office_Hours { get; set; }
        public string Total_TimeSheet_Hours { get; set; }
        public Nullable<decimal> Total_WFH_TimeSheet_Hours { get; set; }
        public string Total_Non__WFH_TimeSheet_Hours { get; set; }
        public string PL_Deduction_Summary { get; set; }
    }
}
