//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyCalculationLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Shift_Time { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public Nullable<decimal> NetWorkingHours { get; set; }
        public Nullable<decimal> Break { get; set; }
        public Nullable<decimal> NetBreak { get; set; }
        public Nullable<System.DateTime> PenaltyDate { get; set; }
        public string PenaltyName { get; set; }
        public Nullable<int> PenaltyID { get; set; }
        public Nullable<int> PenaltyPoint { get; set; }
        public Nullable<int> PenaltyMinuts { get; set; }
        public string PenaltyType { get; set; }
        public Nullable<System.DateTime> CompensactDate { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public Nullable<decimal> DebitBal { get; set; }
        public Nullable<decimal> RemeningBal { get; set; }
        public Nullable<int> AfterCompPenaltyPoint { get; set; }
        public Nullable<int> HeaderID { get; set; }
        public Nullable<int> DetailID { get; set; }
    }
}
