//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyWorkWeekMapping
    {
        public int PolicyWorkWeekMappingID { get; set; }
        public int PolicyID { get; set; }
        public byte WorkWeekTypeID { get; set; }
        public byte WeekDayNameID { get; set; }
        public Nullable<bool> isOne { get; set; }
        public Nullable<bool> isTwo { get; set; }
        public Nullable<bool> isThree { get; set; }
        public Nullable<bool> isFour { get; set; }
        public Nullable<bool> isFive { get; set; }
        public Nullable<bool> isLast { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<byte> StatusID { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual Status Status { get; set; }
        public virtual WeekDayName WeekDayName { get; set; }
        public virtual WorkWeekType WorkWeekType { get; set; }
    }
}
