//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policy()
        {
            this.employees = new HashSet<employee>();
            this.Penalties = new HashSet<Penalty>();
            this.PolicyEligibilityMappings = new HashSet<PolicyEligibilityMapping>();
            this.PolicyLeaveMappings = new HashSet<PolicyLeaveMapping>();
            this.PolicyShiftMappings = new HashSet<PolicyShiftMapping>();
            this.PolicyWorkTimeMappings = new HashSet<PolicyWorkTimeMapping>();
            this.PolicyWorkWeekMappings = new HashSet<PolicyWorkWeekMapping>();
        }
    
        public int PolicyID { get; set; }
        public string DisplayID { get; set; }
        public string PolicyName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public bool isPenaltyApplicable { get; set; }
        public Nullable<byte> SandwichLeaveTypeID { get; set; }
        public bool isDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalty> Penalties { get; set; }
        public virtual SandwichLeaveType SandwichLeaveType { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyEligibilityMapping> PolicyEligibilityMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyLeaveMapping> PolicyLeaveMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyShiftMapping> PolicyShiftMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyWorkTimeMapping> PolicyWorkTimeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyWorkWeekMapping> PolicyWorkWeekMappings { get; set; }
    }
}
