//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyLeaveMapping
    {
        public int PolicyLeaveMappingID { get; set; }
        public int PolicyID { get; set; }
        public short LeaveCategoryID { get; set; }
        public Nullable<byte> SortOrder { get; set; }
        public byte AssignCycleTypeID { get; set; }
        public Nullable<decimal> CycleLeaveLimit { get; set; }
        public Nullable<bool> isCycleStart { get; set; }
        public Nullable<bool> isRoundOffForward { get; set; }
        public Nullable<byte> AccumCycleTypeID { get; set; }
        public Nullable<byte> AccumActionTypeID { get; set; }
        public Nullable<byte> EncashCycleTypeID { get; set; }
        public Nullable<short> EncashMin { get; set; }
        public Nullable<short> EncashMax { get; set; }
        public Nullable<short> EncashAbove { get; set; }
        public Nullable<byte> LeaveAcceptTypeID { get; set; }
        public Nullable<short> LeaveAcceptTerm { get; set; }
        public Nullable<decimal> LeaveAcceptMin { get; set; }
        public Nullable<short> LeaveAcceptMax { get; set; }
        public Nullable<bool> isLeaveClubbing { get; set; }
        public Nullable<bool> isEvidenceRequired { get; set; }
        public Nullable<short> EveidenceTerm { get; set; }
        public Nullable<byte> LeaveApplicableExtent { get; set; }
        public Nullable<byte> LeaveUtilizableExtent { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public Nullable<byte> AssignCycleDay { get; set; }
        public Nullable<bool> isRecalculateLeave { get; set; }
        public Nullable<int> PenaltyPriority { get; set; }
    
        public virtual AccumActionType AccumActionType { get; set; }
        public virtual CycleType CycleType { get; set; }
        public virtual CycleType CycleType1 { get; set; }
        public virtual CycleType CycleType2 { get; set; }
        public virtual ExtentType ExtentType { get; set; }
        public virtual ExtentType ExtentType1 { get; set; }
        public virtual LeaveAcceptType LeaveAcceptType { get; set; }
        public virtual LeaveCategory LeaveCategory { get; set; }
        public virtual Policy Policy { get; set; }
        public virtual Status Status { get; set; }
    }
}
