//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectinitiation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projectinitiation()
        {
            this.projects = new HashSet<project>();
            this.ProjectInitiationPaymentMilestones = new HashSet<ProjectInitiationPaymentMilestone>();
            this.ProjectInitiationResources = new HashSet<ProjectInitiationResource>();
            this.ProjectInitiationResourcesHistories = new HashSet<ProjectInitiationResourcesHistory>();
            this.tblChangeRequestMasters = new HashSet<tblChangeRequestMaster>();
            this.tblPINComments = new HashSet<tblPINComment>();
            this.tblPINDocuments = new HashSet<tblPINDocument>();
            this.tblProjectInitiationLookups = new HashSet<tblProjectInitiationLookup>();
        }
    
        public int ProjectInitiationID { get; set; }
        public string ProjectInitNoteNo { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ProjManagerID { get; set; }
        public int IndustryID { get; set; }
        public int DomainID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> ProjTypeID { get; set; }
        public string DeliverableToClient { get; set; }
        public string AgreementWithClient { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Rate { get; set; }
        public string Cost { get; set; }
        public string paymentTerms { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> IsProjectCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string Remarks { get; set; }
        public string ClientBackground { get; set; }
        public string CostDesc { get; set; }
        public string BillType { get; set; }
        public Nullable<decimal> TEHours { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PanaltyClause { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public bool IP { get; set; }
        public string Directliability { get; set; }
        public string Indirectliability { get; set; }
        public string Jurisdiction { get; set; }
        public Nullable<System.DateTime> AgreementExpiryDate { get; set; }
        public Nullable<int> SupportPeriod { get; set; }
        public Nullable<bool> IsSimilarForAllResource { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<int> AgreementToCompany { get; set; }
        public Nullable<decimal> TechnologyEstimate { get; set; }
        public Nullable<int> NoOfChanges { get; set; }
        public Nullable<decimal> EstimatedEffortofChanges { get; set; }
        public Nullable<int> ProjectInitiationType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ProvToActReminderOn { get; set; }
        public string OpportunityID { get; set; }
        public string RecurringCost { get; set; }
        public Nullable<int> NoOfResources { get; set; }
        public string OneTimeCost { get; set; }
        public string LegalClientName { get; set; }
        public Nullable<System.DateTime> CloseOn { get; set; }
        public Nullable<int> ServiceOfferingID { get; set; }
        public Nullable<int> SalesChannelID { get; set; }
        public string BookingQuarter { get; set; }
        public Nullable<int> EstimatedBy { get; set; }
        public Nullable<int> HierarcyFirstID { get; set; }
        public Nullable<int> HierarcySecondID { get; set; }
        public Nullable<int> HierarcyThirdID { get; set; }
        public Nullable<int> GoToMarrketID { get; set; }
        public Nullable<int> PrimaryRegionID { get; set; }
        public Nullable<int> SecondaryRegionID { get; set; }
        public Nullable<int> BillingPeriod { get; set; }
        public Nullable<bool> IsAdvancePayment { get; set; }
        public string AdvanceAmount { get; set; }
        public Nullable<int> MonthlyHrsLimitMIN { get; set; }
        public Nullable<int> MonthlyHrsLimitMAX { get; set; }
        public Nullable<int> PaymentCycle { get; set; }
        public Nullable<int> PMApprovalStatus { get; set; }
        public Nullable<int> LegalApprovalStatus { get; set; }
        public Nullable<int> SupervisorApprovalStatus { get; set; }
        public string PINStatus { get; set; }
        public Nullable<int> PMApprovalID { get; set; }
        public Nullable<int> LegalApprovalID { get; set; }
        public Nullable<int> SupervisorApprovalID { get; set; }
        public Nullable<int> BookingQuarterYear { get; set; }
        public Nullable<int> BUID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CurrencyDefinition CurrencyDefinition { get; set; }
        public virtual department department { get; set; }
        public virtual domain domain { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual employee employee3 { get; set; }
        public virtual employee employee4 { get; set; }
        public virtual employee employee5 { get; set; }
        public virtual employee employee6 { get; set; }
        public virtual employee employee7 { get; set; }
        public virtual employee employee8 { get; set; }
        public virtual Industry Industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        public virtual tblBillingPeriodMaster tblBillingPeriodMaster { get; set; }
        public virtual tblGoToMarketMaster tblGoToMarketMaster { get; set; }
        public virtual tblPrimaryRegionMaster tblPrimaryRegionMaster { get; set; }
        public virtual projecttype projecttype { get; set; }
        public virtual tblSalesChannelMaster tblSalesChannelMaster { get; set; }
        public virtual tblSecondaryRegionMaster tblSecondaryRegionMaster { get; set; }
        public virtual tblServiceOfferingMaster tblServiceOfferingMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationPaymentMilestone> ProjectInitiationPaymentMilestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResource> ProjectInitiationResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResourcesHistory> ProjectInitiationResourcesHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChangeRequestMaster> tblChangeRequestMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPINComment> tblPINComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPINDocument> tblPINDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectInitiationLookup> tblProjectInitiationLookups { get; set; }
    }
}
