//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectConfigMapping
    {
        public int ProjectConfigMappingID { get; set; }
        public Nullable<byte> ProjectConfigTypeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<byte> StatusID { get; set; }
        public string DisplayValue { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> MinTask { get; set; }
        public Nullable<int> MaxTask { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual project project { get; set; }
        public virtual ProjectConfigType ProjectConfigType { get; set; }
        public virtual Status Status { get; set; }
    }
}
