//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.BusinessAgreements = new HashSet<BusinessAgreement>();
            this.dataentries = new HashSet<dataentry>();
            this.dataentries1 = new HashSet<dataentry>();
            this.DataEntryRejectionHistories = new HashSet<DataEntryRejectionHistory>();
            this.employees = new HashSet<employee>();
            this.Invoices_Project = new HashSet<Invoices_Project>();
            this.milestones = new HashSet<milestone>();
            this.PMSCustomScreens = new HashSet<PMSCustomScreen>();
            this.PMSReleases = new HashSet<PMSRelease>();
            this.PMSWorkflows = new HashSet<PMSWorkflow>();
            this.PMSWorkflowTransitionDatas = new HashSet<PMSWorkflowTransitionData>();
            this.tblActionStepsforMeetings = new HashSet<tblActionStepsforMeeting>();
            this.project1 = new HashSet<project>();
            this.ProjectConfigMappings = new HashSet<ProjectConfigMapping>();
            this.ProjectSprints = new HashSet<ProjectSprint>();
            this.ProjectTechnologyLookups = new HashSet<ProjectTechnologyLookup>();
            this.tblExternalTaskTimesheetImportMappings = new HashSet<tblExternalTaskTimesheetImportMapping>();
            this.tblNotifications = new HashSet<tblNotification>();
            this.tblProjectMeetings = new HashSet<tblProjectMeeting>();
            this.tblProjectStatusQuestions = new HashSet<tblProjectStatusQuestion>();
            this.TeamMembers = new HashSet<TeamMember>();
            this.timeoffrequests = new HashSet<timeoffrequest>();
            this.WBS = new HashSet<WB>();
            this.WBSFiles = new HashSet<WBSFile>();
            this.WBSVersionHistories = new HashSet<WBSVersionHistory>();
        }
    
        public int projectID { get; set; }
        public string proName { get; set; }
        public string code { get; set; }
        public string client { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<decimal> hours { get; set; }
        public int projectStatusID { get; set; }
        public int projectTypeID { get; set; }
        public int domainID { get; set; }
        public int technologyID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> projectCurrentPhaseID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> projectSubTypeID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public Nullable<int> industryID { get; set; }
        public Nullable<int> parentProjectID { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsPSCompulsory { get; set; }
        public bool IsSuspend { get; set; }
        public string Features { get; set; }
        public string keyTechnology { get; set; }
        public Nullable<int> BugTrackingProjectID { get; set; }
        public string DeliverableToClient { get; set; }
        public Nullable<int> InitialSize { get; set; }
        public Nullable<System.DateTime> LastPSRDate { get; set; }
        public string ProjectPhases { get; set; }
        public Nullable<int> SizeAfterClosure { get; set; }
        public Nullable<int> SizeAfterREQM { get; set; }
        public string CaseStudyURL { get; set; }
        public string LiveURL { get; set; }
        public string ProductionURL { get; set; }
        public Nullable<int> ProjectInitNoteID { get; set; }
        public Nullable<bool> IsFilterByTaskAssign { get; set; }
        public Nullable<bool> IsInQueue { get; set; }
        public string MailSentToEmpId { get; set; }
        public Nullable<int> PMMeetingFrequency { get; set; }
        public Nullable<int> PMMeetingFrequencyType { get; set; }
        public Nullable<System.DateTime> NextMeetingDate { get; set; }
        public Nullable<int> MaxTaskHours { get; set; }
        public Nullable<int> MaxStory { get; set; }
        public Nullable<int> ActiveSprints { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<decimal> TechnologyEstimate { get; set; }
        public Nullable<int> NoOfChanges { get; set; }
        public Nullable<decimal> EstimatedEffortofChanges { get; set; }
        public Nullable<int> SprintDuration { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public bool IsWIStatusChangeRestrictedToAssignee { get; set; }
        public Nullable<int> BUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessAgreement> BusinessAgreements { get; set; }
        public virtual Client Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataentry> dataentries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataentry> dataentries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataEntryRejectionHistory> DataEntryRejectionHistories { get; set; }
        public virtual department department { get; set; }
        public virtual domain domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employees { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual Industry Industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices_Project> Invoices_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<milestone> milestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSCustomScreen> PMSCustomScreens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSRelease> PMSReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflow> PMSWorkflows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransitionData> PMSWorkflowTransitionDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActionStepsforMeeting> tblActionStepsforMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> project1 { get; set; }
        public virtual project project2 { get; set; }
        public virtual projectinitiation projectinitiation { get; set; }
        public virtual projectstatu projectstatu { get; set; }
        public virtual projectstatu projectstatu1 { get; set; }
        public virtual projectsubtype projectsubtype { get; set; }
        public virtual projecttype projecttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectConfigMapping> ProjectConfigMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSprint> ProjectSprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTechnologyLookup> ProjectTechnologyLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExternalTaskTimesheetImportMapping> tblExternalTaskTimesheetImportMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectMeeting> tblProjectMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectStatusQuestion> tblProjectStatusQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeoffrequest> timeoffrequests { get; set; }
        public virtual TblProjectTemplate TblProjectTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WB> WBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBSFile> WBSFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBSVersionHistory> WBSVersionHistories { get; set; }
    }
}
