//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInitiationResource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectInitiationResource()
        {
            this.ProjectInitiationResourcesHistories = new HashSet<ProjectInitiationResourcesHistory>();
        }
    
        public int ProjectInitiationResourcesId { get; set; }
        public int ProjectInitiationId { get; set; }
        public int RoleId { get; set; }
        public Nullable<decimal> NoOfResources { get; set; }
        public string BillingType { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> MonthlyBillingHours { get; set; }
        public decimal Amount { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> TechnologyID { get; set; }
        public Nullable<int> SubcontractorID { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public Nullable<System.DateTime> BillingEndDate { get; set; }
        public string AdditionalNotes { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual projectinitiation projectinitiation { get; set; }
        public virtual role role { get; set; }
        public virtual role role1 { get; set; }
        public virtual tblSubContractorMaster tblSubContractorMaster { get; set; }
        public virtual technology technology { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResourcesHistory> ProjectInitiationResourcesHistories { get; set; }
    }
}
