//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInitiationResourcesHistory
    {
        public int ProjectInitiationResourcesHistoryId { get; set; }
        public int ProjectInitiationResourcesId { get; set; }
        public int ProjectInitiationId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> NoOfResources { get; set; }
        public string BillingType { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> MonthlyBillingHours { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual projectinitiation projectinitiation { get; set; }
        public virtual ProjectInitiationResource ProjectInitiationResource { get; set; }
        public virtual role role { get; set; }
    }
}
