//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendanceReportPLBalance
    {
        public int AttendanceReportPLBalanceId { get; set; }
        public int AttendanceReportParameterId { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<double> OpeningPLBalance { get; set; }
        public System.DateTime ApplicationDate { get; set; }
    
        public virtual AttendanceReprotParameter AttendanceReprotParameter { get; set; }
        public virtual employee employee { get; set; }
    }
}
