//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditLogTableColumn
    {
        public int ID { get; set; }
        public int TableNameID { get; set; }
        public string ColumnName { get; set; }
    
        public virtual tblAuditLogTable tblAuditLogTable { get; set; }
    }
}
