//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnswerOption
    {
        public int AnswerOptionID { get; set; }
        public int QuestionID { get; set; }
        public string OptionText { get; set; }
        public bool Deleted { get; set; }
    }
}
