//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        public int AreaID { get; set; }
        public string AreaKey { get; set; }
        public string AreaName { get; set; }
        public System.DateTime AreaCreatedDate { get; set; }
        public int AreaCreatedBy { get; set; }
        public Nullable<System.DateTime> AreaModifiedDate { get; set; }
        public Nullable<int> AreaModifiedBy { get; set; }
    }
}
