//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSchedule
    {
        public int EmployeeScheduleID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public byte EmployeeScheduleType { get; set; }
        public Nullable<byte> EmployeeScheduleSeq { get; set; }
        public Nullable<short> EmployeeScheduleTimeInterval { get; set; }
        public Nullable<byte> EmployeeScheduleTimeIntervalOp { get; set; }
        public Nullable<System.DateTime> EmployeeScheduleStartDate { get; set; }
        public Nullable<System.DateTime> EmployeeScheduleEndDate { get; set; }
        public Nullable<System.DateTime> EmployeeScheduleNonStartDate { get; set; }
        public string EmployeeScheduleNonStartTime { get; set; }
        public string EmployeeScheduleNonDayDuration { get; set; }
        public string EmployeeScheduleNonRestDuration { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual tblSchedule tblSchedule { get; set; }
    }
}
