//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExternalTaskTimesheetImportMapping
    {
        public int ExternalTimesheetImportMappingID { get; set; }
        public int ProjectID { get; set; }
        public string ConfigData { get; set; }
        public string ConfigName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> NumberOfRowsExcel { get; set; }
        public Nullable<int> NumberOfUniqueTask { get; set; }
        public Nullable<int> NumberOfTaskInserted { get; set; }
        public Nullable<int> NumberOfTaskUpdated { get; set; }
        public Nullable<int> NumberOfTimeSheetInserted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string InsertedTaskID { get; set; }
        public string UpdatedTaskID { get; set; }
        public string InsertedTimesheetID { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual project project { get; set; }
    }
}
