//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIterationHistory
    {
        public int ID { get; set; }
        public System.DateTime OldEndDate { get; set; }
        public System.DateTime NewEndDate { get; set; }
        public string Reason { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> IterationId { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual ProjectSprint ProjectSprint { get; set; }
    }
}
