//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInOutAdjustment
    {
        public int ID { get; set; }
        public int EmpInOutID { get; set; }
        public int TimeOffRequestID { get; set; }
        public System.DateTime InTime { get; set; }
        public System.DateTime OutTime { get; set; }
        public Nullable<int> AttendanceType { get; set; }
    
        public virtual timeoffrequest timeoffrequest { get; set; }
    }
}
