//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKRASetting
    {
        public int tblKRASettingsID { get; set; }
        public string SettingsObjectName { get; set; }
        public string SettingsEntityName { get; set; }
        public string SettingsEntityValue { get; set; }
        public bool SettingsStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte[] DateModified { get; set; }
    }
}
