//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKRAAssignDetailKPI
    {
        public int KRAAssignDetailKPIId { get; set; }
        public int KRAAssignDetailId { get; set; }
        public int KPIId { get; set; }
    
        public virtual tblKPI tblKPI { get; set; }
        public virtual tblKRAAssignDetail tblKRAAssignDetail { get; set; }
    }
}
