//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKRAEVLPrdSetting
    {
        public int KRAEVLPrdSettingsID { get; set; }
        public int EvalutionFrequencyId { get; set; }
        public int SettingsLevel { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> ApprovalDeadline { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte[] DateModified { get; set; }
        public int DateType { get; set; }
        public string ScoringCycles { get; set; }
        public Nullable<int> SelectedMonth { get; set; }
    
        public virtual tblEvalutionFrequency tblEvalutionFrequency { get; set; }
    }
}
