//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKRAKPI_Relation
    {
        public int KRAKPIId { get; set; }
        public int KPIId { get; set; }
        public int KRAID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedById { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual tblKPI tblKPI { get; set; }
        public virtual tblKRAMaster tblKRAMaster { get; set; }
    }
}
