//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKRAAssignDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKRAAssignDetail()
        {
            this.tblEvaluationComments = new HashSet<tblEvaluationComment>();
            this.tblKRAAssignDetailEVlParams = new HashSet<tblKRAAssignDetailEVlParam>();
            this.tblKRAAssignDetailKPIs = new HashSet<tblKRAAssignDetailKPI>();
            this.tblKRAScores = new HashSet<tblKRAScore>();
        }
    
        public int KRAAssignDetailId { get; set; }
        public int KRAAssignId { get; set; }
        public int KRAId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public Nullable<int> Weightage { get; set; }
        public string Notes { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEvaluationComment> tblEvaluationComments { get; set; }
        public virtual tblKRAAssign tblKRAAssign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssignDetailEVlParam> tblKRAAssignDetailEVlParams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAAssignDetailKPI> tblKRAAssignDetailKPIs { get; set; }
        public virtual tblKRAMaster tblKRAMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKRAScore> tblKRAScores { get; set; }
    }
}
