//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKRAScore
    {
        public int KRAScoreId { get; set; }
        public Nullable<int> AssignEvaluationDatesId { get; set; }
        public Nullable<int> KRAAssignDetailId { get; set; }
        public Nullable<int> IndividualScore { get; set; }
        public Nullable<int> SupervisorScore { get; set; }
        public Nullable<int> ManagerScore { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte[] DateModified { get; set; }
    
        public virtual tblKRAAssignDetail tblKRAAssignDetail { get; set; }
        public virtual tblKRAAssignEvaluationDate tblKRAAssignEvaluationDate { get; set; }
    }
}
