//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNotification()
        {
            this.tblNotificationUsers = new HashSet<tblNotificationUser>();
        }
    
        public int NotificationId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SprintId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string NotificationMessage { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string NotificationTitle { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual project project { get; set; }
        public virtual ProjectSprint ProjectSprint { get; set; }
        public virtual WB WB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotificationUser> tblNotificationUsers { get; set; }
    }
}
