//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrgLevelBandTiersLookup
    {
        public int Id { get; set; }
        public int LevelId { get; set; }
        public int BandId { get; set; }
        public int TiersId { get; set; }
        public int Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual tblOrgBandMaster tblOrgBandMaster { get; set; }
        public virtual tblOrgLevelMaster tblOrgLevelMaster { get; set; }
        public virtual tblOrgTiersMaster tblOrgTiersMaster { get; set; }
    }
}
