//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageTracker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPageTracker()
        {
            this.tblPageTrackingSummaries = new HashSet<tblPageTrackingSummary>();
        }
    
        public int PageTrackerID { get; set; }
        public Nullable<int> PTEmpId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeHostAddress { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public string EmployeeAgent { get; set; }
        public string BrowserName { get; set; }
        public string URLVisitedFrom { get; set; }
        public Nullable<bool> IsLoggedFromCygnet { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPageTrackingSummary> tblPageTrackingSummaries { get; set; }
    }
}
