//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingFeedbackQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTrainingFeedbackQuestion()
        {
            this.tblTrainingFeedBackAnswers = new HashSet<tblTrainingFeedBackAnswer>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public int AnswerType { get; set; }
        public Nullable<int> QuestionCategory { get; set; }
        public int QuestionFor { get; set; }
        public bool IsRequired { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual tblQuestionCategory tblQuestionCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedBackAnswer> tblTrainingFeedBackAnswers { get; set; }
    }
}
