//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingNomination
    {
        public int Id { get; set; }
        public int TrainingId { get; set; }
        public int NominatedEmpId { get; set; }
        public bool IsAddedInTraining { get; set; }
        public int NominatedBy { get; set; }
        public System.DateTime NominationDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual TrainingMaster TrainingMaster { get; set; }
    }
}
