//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamMemberKraNote
    {
        public int TeamMemberKraNotesID { get; set; }
        public Nullable<int> TeamMemberId { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> NotesType { get; set; }
    
        public virtual TeamMember TeamMember { get; set; }
    }
}
