//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingWaiverDetail
    {
        public int WaiverDetailID { get; set; }
        public int WaiverID { get; set; }
        public long TrainingDetailID { get; set; }
        public string Reason { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual tblTrainingWaiverMaster tblTrainingWaiverMaster { get; set; }
        public virtual TrainingDetail TrainingDetail { get; set; }
    }
}
