//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskRemainingHourDetail
    {
        public int TaskRemainigHourId { get; set; }
        public int WBSId { get; set; }
        public int SprintId { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public Nullable<int> StoryId { get; set; }
        public int EstimatedHour { get; set; }
        public int RemainingHour { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> WorkingDate { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual ProjectSprint ProjectSprint { get; set; }
        public virtual tblTaskStatu tblTaskStatu { get; set; }
        public virtual WB WB { get; set; }
        public virtual WB WB1 { get; set; }
    }
}
