//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTempPunchData_SinglePunch_Day
    {
        public int ID { get; set; }
        public string empCode { get; set; }
        public System.DateTime PDate { get; set; }
        public Nullable<System.DateTime> punch1 { get; set; }
        public Nullable<System.DateTime> punch2 { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
