//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTaskStatu()
        {
            this.PMSWorkflowTransitions = new HashSet<PMSWorkflowTransition>();
            this.PMSWorkflowTransitions1 = new HashSet<PMSWorkflowTransition>();
            this.PMSWorkflowTransitionDatas = new HashSet<PMSWorkflowTransitionData>();
            this.PMSWorkflowTransitionDatas1 = new HashSet<PMSWorkflowTransitionData>();
            this.tblActivityDetails = new HashSet<tblActivityDetail>();
            this.tblActivityDetails1 = new HashSet<tblActivityDetail>();
            this.tblTaskRemainingHourDetails = new HashSet<tblTaskRemainingHourDetail>();
            this.WBS = new HashSet<WB>();
        }
    
        public int TaskStatusId { get; set; }
        public string DisplayValue { get; set; }
        public Nullable<int> wbsid { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> SequenceId { get; set; }
        public string Title { get; set; }
        public Nullable<int> MinTasks { get; set; }
        public Nullable<int> MaxTasks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Description { get; set; }
        public string IconPath { get; set; }
        public bool IsSystemDefine { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransition> PMSWorkflowTransitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransition> PMSWorkflowTransitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransitionData> PMSWorkflowTransitionDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransitionData> PMSWorkflowTransitionDatas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivityDetail> tblActivityDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivityDetail> tblActivityDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskRemainingHourDetail> tblTaskRemainingHourDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WB> WBS { get; set; }
        public virtual WB WB { get; set; }
    }
}
