//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVisitedPageDetail
    {
        public int VisitedPageDetailID { get; set; }
        public Nullable<int> VisitedPageID { get; set; }
        public string VisitedPage { get; set; }
        public Nullable<System.TimeSpan> ElapsedTime { get; set; }
    
        public virtual tblPageTrackingSummary tblPageTrackingSummary { get; set; }
    }
}
