//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamMember()
        {
            this.KRAEvaluations = new HashSet<KRAEvaluation>();
            this.tblTeamMemberKraEvalutions = new HashSet<tblTeamMemberKraEvalution>();
            this.tblTeamMemberKraNotes = new HashSet<tblTeamMemberKraNote>();
        }
    
        public int TeamMemersID { get; set; }
        public int ProjectID { get; set; }
        public int RoleID { get; set; }
        public int EmpID { get; set; }
        public bool IsTimeSheetApprove { get; set; }
        public bool IsTimeoffReceiveMails { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Utilization { get; set; }
        public Nullable<int> PrivilegeId { get; set; }
        public Nullable<bool> CanApproveDataEntry { get; set; }
        public Nullable<int> KPIApprovalStatus { get; set; }
        public Nullable<int> EvaluationPeriod { get; set; }
        public Nullable<int> KraCreateBy { get; set; }
        public Nullable<int> KraUpdateBy { get; set; }
        public Nullable<System.DateTime> KraCreateOn { get; set; }
        public Nullable<System.DateTime> KraUpdateOn { get; set; }
        public Nullable<bool> Is_PM_for_ProjectMeeting { get; set; }
        public Nullable<bool> CanApproveKRA { get; set; }
        public bool IsResoureceManagement { get; set; }
        public Nullable<int> UtilizationType { get; set; }
        public string Remarks { get; set; }
        public bool IsNotBillable { get; set; }
        public bool IsRoleAsPerCompanyRole { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KRAEvaluation> KRAEvaluations { get; set; }
        public virtual PrivilegeRole PrivilegeRole { get; set; }
        public virtual project project { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamMemberKraEvalution> tblTeamMemberKraEvalutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTeamMemberKraNote> tblTeamMemberKraNotes { get; set; }
    }
}
