//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class technology
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public technology()
        {
            this.EmployeeCompetencyDetails = new HashSet<EmployeeCompetencyDetail>();
            this.EmployeeSkillDetails = new HashSet<EmployeeSkillDetail>();
            this.ProjectInitiationResources = new HashSet<ProjectInitiationResource>();
            this.tblSkillRatings = new HashSet<tblSkillRating>();
            this.technology1 = new HashSet<technology>();
        }
    
        public int technologyID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> parenttechnologyid { get; set; }
        public Nullable<int> technologytypeid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCompetencyDetail> EmployeeCompetencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkillDetail> EmployeeSkillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectInitiationResource> ProjectInitiationResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSkillRating> tblSkillRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<technology> technology1 { get; set; }
        public virtual technology technology2 { get; set; }
        public virtual technologytype technologytype { get; set; }
    }
}
