//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempRep
    {
        public int id { get; set; }
        public Nullable<int> empid_Output { get; set; }
        public Nullable<System.DateTime> workdate_Output { get; set; }
        public Nullable<decimal> Timesheet_Hours_Output { get; set; }
        public Nullable<decimal> DataEntryHours_Output { get; set; }
        public Nullable<decimal> TotalIdleTIme_Output { get; set; }
        public string EmpName_Output { get; set; }
    }
}
