//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeoffrequest_temp
    {
        public int TempID { get; set; }
        public int TimeOffRequestID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public Nullable<int> HalfDayType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ContactNo { get; set; }
        public string ReasonForTimeOff { get; set; }
        public decimal NoOfDays { get; set; }
        public string NoOfDayMonthWise { get; set; }
        public string Months { get; set; }
        public Nullable<int> TimeOffStatus { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> ApprovedByID { get; set; }
        public string ApprovedDate { get; set; }
        public string Remarks { get; set; }
        public int ApprovalTypeId { get; set; }
        public Nullable<int> minutes { get; set; }
    
        public virtual ApprovalType ApprovalType { get; set; }
    }
}
