//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeOffRequestClone
    {
        public int TimeOffRequestTempID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> TimOffDate { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public Nullable<int> TimeOffStatus { get; set; }
        public Nullable<int> TimeOffRequestID { get; set; }
        public int ApprovalTypeId { get; set; }
        public Nullable<int> minutes { get; set; }
    
        public virtual ApprovalType ApprovalType { get; set; }
    }
}
