//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeoffrequest_LOG
    {
        public int ID { get; set; }
        public Nullable<int> TimeOffRequestID { get; set; }
        public Nullable<int> Old_EmpID { get; set; }
        public Nullable<int> New_EmpID { get; set; }
        public Nullable<System.DateTime> Old_FromDate { get; set; }
        public Nullable<System.DateTime> New_FromDate { get; set; }
        public Nullable<System.DateTime> Old_ToDate { get; set; }
        public Nullable<System.DateTime> New_ToDate { get; set; }
        public string Old_Reason { get; set; }
        public string New_Reason { get; set; }
        public Nullable<decimal> Old_NoOfDays { get; set; }
        public Nullable<decimal> New_NoOfDays { get; set; }
        public Nullable<int> Old_TimeOfStatus { get; set; }
        public Nullable<int> New_TimeOfStatus { get; set; }
        public Nullable<int> Old_ApprovalTypeID { get; set; }
        public Nullable<int> New_ApprovalTypeID { get; set; }
        public Nullable<int> Old_ProjectID { get; set; }
        public Nullable<int> New_ProjectID { get; set; }
        public Nullable<int> Old_IsWFH { get; set; }
        public Nullable<int> New_IsWFH { get; set; }
        public Nullable<int> Old_ParentID { get; set; }
        public Nullable<int> New_ParentID { get; set; }
        public Nullable<System.DateTime> Old_UpdatedDate { get; set; }
        public Nullable<System.DateTime> New_UpdatedDate { get; set; }
        public Nullable<System.DateTime> Old_CreatedDate { get; set; }
        public Nullable<System.DateTime> New_CreatedDate { get; set; }
        public Nullable<int> Old_Minutes { get; set; }
        public Nullable<int> New_Minutes { get; set; }
        public Nullable<System.DateTime> Old_ApprovedDate { get; set; }
        public Nullable<System.DateTime> New_ApprovedDate { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public string ServerIPAddr { get; set; }
        public string ClientIPAddr { get; set; }
        public string PROG_NAME { get; set; }
    }
}
