//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingMaster()
        {
            this.tblTrainingFeedBackMasters = new HashSet<tblTrainingFeedBackMaster>();
            this.tblTrainingNominations = new HashSet<tblTrainingNomination>();
            this.tblTrainingWaiverMasters = new HashSet<tblTrainingWaiverMaster>();
            this.TrainingDetails = new HashSet<TrainingDetail>();
            this.TrainingDetailsLogs = new HashSet<TrainingDetailsLog>();
            this.TrainingEvaluations = new HashSet<TrainingEvaluation>();
            this.TrainingMasterLogs = new HashSet<TrainingMasterLog>();
        }
    
        public int TrainingId { get; set; }
        public string TrainingName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> TrainingCategoryId { get; set; }
        public Nullable<int> EvaluationMethod { get; set; }
        public Nullable<decimal> EvaluationPeriod { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> TrainingType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> FeedbackPer { get; set; }
        public string TrainingObjective { get; set; }
        public string TrainingTopic { get; set; }
        public bool IsBeforeRating { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<bool> IsAttendanceLock { get; set; }
        public Nullable<bool> AttendanceFillByEmployee { get; set; }
        public Nullable<bool> IsEventOnPremise { get; set; }
        public Nullable<int> OccurrenceType { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public Nullable<bool> IsSunday { get; set; }
        public Nullable<bool> IsMonday { get; set; }
        public Nullable<bool> IsTuesday { get; set; }
        public Nullable<bool> IsWednesday { get; set; }
        public Nullable<bool> IsThursday { get; set; }
        public Nullable<bool> IsFriday { get; set; }
        public Nullable<bool> IsSaturday { get; set; }
        public Nullable<bool> IsWeekDayOfMonth { get; set; }
        public Nullable<int> DayOfEvryMonth { get; set; }
        public Nullable<int> WeekDayType { get; set; }
        public Nullable<int> WeekDayNameId { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.DateTime> OccurenceStartDate { get; set; }
        public Nullable<System.DateTime> OccurenceEndDate { get; set; }
        public Nullable<bool> IsEventPublic { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual Lookup Lookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingFeedBackMaster> tblTrainingFeedBackMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingNomination> tblTrainingNominations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainingWaiverMaster> tblTrainingWaiverMasters { get; set; }
        public virtual TrainingCategory TrainingCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingDetail> TrainingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingDetailsLog> TrainingDetailsLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingEvaluation> TrainingEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingMasterLog> TrainingMasterLogs { get; set; }
    }
}
