//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMasterLog
    {
        public int TrainingLogID { get; set; }
        public int TrainingID { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsChange { get; set; }
        public bool IsMasterChange { get; set; }
        public bool IsEvaluationMailSend { get; set; }
    
        public virtual TrainingMaster TrainingMaster { get; set; }
    }
}
