//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeDetail
    {
        public int TraineeId { get; set; }
        public long TrainingDetailId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<bool> IsVisited { get; set; }
        public int BeforeRating { get; set; }
        public int AfterRating { get; set; }
        public bool IsFeedback { get; set; }
        public string ReasonForDifferenceInRating { get; set; }
        public Nullable<int> TrainerRating { get; set; }
        public Nullable<int> TrainingFacilityRating { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual TrainingDetail TrainingDetail { get; set; }
    }
}
