//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingEvaluation
    {
        public int TrainingEvaluationID { get; set; }
        public int TrainingID { get; set; }
        public int ReportingManagerID { get; set; }
        public string FileName { get; set; }
        public byte[] content { get; set; }
        public string doctype { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual TrainingMaster TrainingMaster { get; set; }
    }
}
