//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TrainerDetail
    {
        public long TrainerId { get; set; }
        public long TrainingDetailId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ExternalTrainerId { get; set; }
        public Nullable<int> TrainerType { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
    }
}
