//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWR_PINData
    {
        public string ProjectInitNoteNo { get; set; }
        public string ClientName { get; set; }
        public string PIN_Type { get; set; }
        public string SalesPersonName { get; set; }
        public string ProjectManager { get; set; }
        public string Project_Type { get; set; }
        public string BillType { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<decimal> No_Of_Resources { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string HourlyRate { get; set; }
        public string Cost { get; set; }
        public string Cost_Description { get; set; }
        public string Payment_Terms { get; set; }
        public string PanaltyClause { get; set; }
    }
}
