//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WB()
        {
            this.dataentries = new HashSet<dataentry>();
            this.dataentries1 = new HashSet<dataentry>();
            this.DataEntryRejectionHistories = new HashSet<DataEntryRejectionHistory>();
            this.PMSWorkflowTransitionDatas = new HashSet<PMSWorkflowTransitionData>();
            this.tblActivityDetails = new HashSet<tblActivityDetail>();
            this.tblEmployeeWbsLookups = new HashSet<tblEmployeeWbsLookup>();
            this.tblNotifications = new HashSet<tblNotification>();
            this.tblTaskComments = new HashSet<tblTaskComment>();
            this.tblTaskRemainingHourDetails = new HashSet<tblTaskRemainingHourDetail>();
            this.tblTaskRemainingHourDetails1 = new HashSet<tblTaskRemainingHourDetail>();
            this.tblTaskStatus = new HashSet<tblTaskStatu>();
            this.WBS1 = new HashSet<WB>();
            this.WBSEmpLinks = new HashSet<WBSEmpLink>();
        }
    
        public int WBSID { get; set; }
        public int WBSVersionHistoryID { get; set; }
        public int UniqueID { get; set; }
        public string WBSParentName { get; set; }
        public string WBSName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> EstimatedHours { get; set; }
        public Nullable<System.DateTime> EstimatedStartDate { get; set; }
        public Nullable<System.DateTime> EstimatedEndDate { get; set; }
        public Nullable<int> ActualHours { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string ResourceNames { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Description { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public Nullable<int> UniqueParentID { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string AttachDocument { get; set; }
        public string Assignee { get; set; }
        public string ExternalTaskID { get; set; }
        public string Tags { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SprintId { get; set; }
        public string Viewer { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> SuggestionId { get; set; }
        public string Predecessor { get; set; }
        public Nullable<int> PercentageCompleted { get; set; }
        public Nullable<int> ReleaseId { get; set; }
        public Nullable<decimal> ResourceUnit { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataentry> dataentries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dataentry> dataentries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataEntryRejectionHistory> DataEntryRejectionHistories { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowTransitionData> PMSWorkflowTransitionDatas { get; set; }
        public virtual project project { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }
        public virtual ProjectPriority ProjectPriority1 { get; set; }
        public virtual ProjectSprint ProjectSprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActivityDetail> tblActivityDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeWbsLookup> tblEmployeeWbsLookups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
        public virtual tblSuggestion tblSuggestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskComment> tblTaskComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskRemainingHourDetail> tblTaskRemainingHourDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskRemainingHourDetail> tblTaskRemainingHourDetails1 { get; set; }
        public virtual tblTaskStatu tblTaskStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaskStatu> tblTaskStatus { get; set; }
        public virtual WorkItemMaster WorkItemMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WB> WBS1 { get; set; }
        public virtual WB WB1 { get; set; }
        public virtual WB WBS11 { get; set; }
        public virtual WB WB2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBSEmpLink> WBSEmpLinks { get; set; }
    }
}
