//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBS_Test
    {
        public int WBSID { get; set; }
        public int WBSVersionHistoryID { get; set; }
        public int UniqueID { get; set; }
        public string WBSParentName { get; set; }
        public string WBSName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> EstimatedHours { get; set; }
        public Nullable<System.DateTime> EstimatedStartDate { get; set; }
        public Nullable<System.DateTime> EstimatedEndDate { get; set; }
        public Nullable<int> ActualHours { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string ResourceNames { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Description { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public Nullable<int> UniqueParentID { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string AttachDocument { get; set; }
        public string Assignee { get; set; }
        public string ExternalTaskID { get; set; }
        public string Tags { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SprintId { get; set; }
        public string Viewer { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> SuggestionId { get; set; }
        public string Predecessor { get; set; }
        public Nullable<int> PercentageCompleted { get; set; }
        public Nullable<int> ReleaseId { get; set; }
        public Nullable<decimal> ResourceUnit { get; set; }
    }
}
