//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSEmpLink
    {
        public int WBSEmpLinkID { get; set; }
        public Nullable<int> WBSID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> Utilization { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual WB WB { get; set; }
    }
}
