//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSFile
    {
        public int PSFID { get; set; }
        public string PSFileName { get; set; }
        public Nullable<bool> IsProceed { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual project project { get; set; }
    }
}
