//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBSVersionHistory
    {
        public int WBSVersionHistoryID { get; set; }
        public int ProjectID { get; set; }
        public string PSFileName { get; set; }
        public decimal Version { get; set; }
        public int PreparedBy { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string DescriptionOfChange { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual project project { get; set; }
        public virtual WBSVersionHistory WBSVersionHistory1 { get; set; }
        public virtual WBSVersionHistory WBSVersionHistory2 { get; set; }
    }
}
