//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItemMaster()
        {
            this.PMSWorkflowWorkItemMappings = new HashSet<PMSWorkflowWorkItemMapping>();
            this.WBS = new HashSet<WB>();
        }
    
        public int WorkItemID { get; set; }
        public string WorkItemName { get; set; }
        public string Description { get; set; }
        public bool IsAgile { get; set; }
        public bool IsAgileDefault { get; set; }
        public bool IsKanban { get; set; }
        public bool IsKanbanDefault { get; set; }
        public bool IsIterative { get; set; }
        public bool IsIterativeDefault { get; set; }
        public bool IsActive { get; set; }
        public bool IsSystemDefined { get; set; }
        public string IconName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSWorkflowWorkItemMapping> PMSWorkflowWorkItemMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WB> WBS { get; set; }
    }
}
